

-- Add the module to the tree
local mod = aegis
local me = {}
mod.skills = me

me.myevents = {
    "CHAT_MSG_COMBAT_SELF_MISSES",  -- 你未命中一个生物时触发
    "CHAT_MSG_SPELL_SELF_DAMAGE",  -- 你施放一个法术伤害时触发
    "CHAT_MSG_SPELL_DAMAGESHIELDS_ON_SELF",  -- 当一个 buff (或可能的物品) 对对手的行为造成伤害... 如荆棘术.

    "CHAT_MSG_SPELL_CREATURE_VS_CREATURE_DAMAGE",
    "CHAT_MSG_SPELL_HOSTILEPLAYER_BUFF",
    "CHAT_MSG_SPELL_CREATURE_VS_CREATURE_BUFF",
    "CHAT_MSG_SPELL_HOSTILEPLAYER_DAMAGE",

    "CHAT_MSG_SPELL_SELF_DAMAGE",
    "CHAT_MSG_COMBAT_SELF_MISSES",

    "CHAT_MSG_SPELL_PERIODIC_SELF_DAMAGE",
    "CHAT_MSG_SPELL_AURA_GONE_SELF",

    "CHAT_MSG_COMBAT_CREATURE_VS_SELF_MISSES",

    "PLAYER_TARGET_CHANGED",
    "CHARACTER_POINTS_CHANGED",

    "CHAT_MSG_SPELL_FAILED_LOCALPLAYER",

    }