aegis.string.data["zhCN"] = {
    ["class"] = {
        ["druid"]			    = "德鲁伊",
        ["hunter"]			    = "猎人",
        ["mage"]			    = "法师",
        ["paladin"]			    = "圣骑士",
        ["priest"]			    = "牧师",
        ["rogue"]			    = "盗贼",
        ["shaman"]			    = "萨满祭司",
        ["warlock"]			    = "术士",
        ["warrior"]			    = "战士",
    },
    ["item_type"] = {
        ["shield"] = "盾牌",
        ["bow"] = "弓",
        ["crossbow"] = "弩",
        ["gun"] = "枪",
        ["thrown"] = "投掷武器",
    },
    ["race"] = {
        ["dwarf"]				= "矮人",
        ["orc"]				    = "兽人",
        ["tauren"]              = "牛头人",
        ["troll"]				= "巨魔",
    },
    ["spell"] = {
        ["battle_shout"]		= "战斗怒吼",
        ["battle_stance"]		= "战斗姿态",
        ["berserker_rage"]		= "狂暴之怒",
        ["berserker_stance"]	= "狂暴姿态",
        ["blood"]				= "血性狂暴",
        ["bloodrage"]			= "血性狂暴",
        ["bloodthirst"]		    = "嗜血",
        ["challenging_shout"]	= "挑战怒吼",
        ["charge"]				= "冲锋",
        ["cleave"]				= "顺劈斩",
        ["concussion_blow"]	    = "震荡猛击",
        ["death_wish"]			= "死亡之愿",
        ["defensive_stance"]	= "防御姿态",
        ["demoralizing_shout"]	= "挫志怒吼",
        ["disarm"]				= "缴械",
        ["execute"]			    = "斩杀",
        ["hamstring"]			= "断筋",
        ["heroic_strike"]		= "英勇打击",
        ["intercept"]			= "拦截",
        ["intimidating_shout"]	= "破胆怒吼",
        ["last_stand"]			= "破釜沉舟",
        ["mocking_blow"]		= "惩戒痛击",
        ["mortal_strike"]		= "致死打击",
        ["overpower"]			= "压制",
        ["piercing_howl"]		= "刺耳怒吼",
        ["pummel"]				= "拳击",
        ["recklessness"]		= "鲁莽",
        ["rend"]				= "撕裂",
        ["retaliation"]		    = "反击风暴",
        ["revenge"]			    = "复仇",
        ["shield_bash"]		    = "盾击",
        ["shield_block"]		= "盾牌格挡",
        ["shield_slam"]		    = "盾牌猛击",
        ["shield_wall"]		    = "盾墙",
        ["slam"]				= "猛击",
        ["shoot_bow"]			= "弓射击",
        ["shoot_crossbow"]		= "弩射击",
        ["shoot_gun"]			= "枪械射击",
        ["stoneform"]			= "石像形态",
        ["sunder_armor"]		= "破甲攻击",
        ["sweeping_strikes"]	= "横扫攻击",
        ["taunt"]				= "嘲讽",
        ["thunder_clap"]		= "雷霆一击",
        ["throw"]				= "投掷",
        ["whirlwind"]			= "旋风斩",
    },
    ["combat"] = {
        ["disarmed"] = {
            ["enable"] = {
                "你受到了缴械效果的影响。",
                "你受到了丢弃武器效果的影响。",
            },
            ["disable"] = {
                "缴械效果从你身上消失了。",
                "丢弃武器效果从你身上消失了。",
            },
        },
        ["fear"] = {
            ["enable"] = {
                "你受到了恐惧术效果的影响。",
                "你受到了破胆怒吼效果的影响。",
                "你受到了心灵尖啸效果的影响。",
                "你受到了恐慌效果的影响。",
                "你受到了低沉咆哮效果的影响。",
                "你受到了上古绝望效果的影响。",
                "你受到了恐吓尖啸效果的影响。",
                "你受到了恐惧嚎叫效果的影响。",
            },
            ["disable"] = {
                "恐惧术效果从你身上消失了。",
                "破胆怒吼效果从你身上消失了。",
                "心灵尖啸效果从你身上消失了。",
                "恐慌效果从你身上消失了。",
                "低沉咆哮效果从你身上消失了。",
                "上古绝望效果从你身上消失了。",
                "恐吓尖啸效果从你身上消失了。",
                "恐惧嚎叫效果从你身上消失了。",
            },
        },
        ["incapacitated"] = {
            ["enable"] = {
                "你受到了闷棍效果的影响。",
                "你受到了凿击效果的影响。",
                "你受到了忏悔效果的影响。",
                "你受到了无畏冲锋效果的影响。"
            },
            ["disable"] = {
                "闷棍效果从你身上消失了。",
                "凿击效果从你身上消失了。",
                "忏悔效果从你身上消失了。",
                "无畏冲锋效果从你身上消失了。"
            },
        },
        ["interrupt"] = {
            ["enable"] = "(.+)开始施放(.+)。",
            ["success"] = "你打断了(.+)。",
            ["failure"] = {
                "你的拳击被(.+)招架了。",
                "你的拳击被(.+)格挡了。",
                "你的拳击被(.+)躲闪过去了。",
                "你的盾击被(.+)招架了。",
                "你的盾击被(.+)格挡了。",
                "你的盾击被(.+)躲闪过去了。",
                "你的拳击没有击中(.+)。",
                "你的盾击没有击中(.+)。",
            }
        },
        ["overpower"] = {
            ["enable"] = {
                "你发起了攻击。(.+)闪开了。",
                "你的(.+)被(.+)躲闪过去了。"
            },
            ["disable"] = {
                "你的压制对(.+)造成(%d+)的致命一击伤害。",
                "你的压制击中(.+)造成(%d+)点伤害。",
                "你的压制没有击中(.+)。"
            }
        },
        ["runaway"] = {"%s充满恐惧地想要转身逃跑！"},
        ["revenge"] = {
            ["enable"] = {
                "你闪躲开了",
                "你招架住了",
                "你格挡开了",
            },
            ["disable"] = {
                "你的复仇对(.+)造成(%d+)的致命一击伤害。",
                "你的复仇击中(.+)造成(%d+)点伤害。",
                "你的复仇被(.+)招架了。",
                "你的复仇被(.+)格挡了。",
                "你的复仇被(.+)躲闪过去了。",
                "你的复仇没有击中(.+)。"
                }
            },
    },
    ["translation"] = {
        ["Shield Slam is almost ready, wait"] = "盾牌猛击即将就绪，等待。",
    },
}

aegis.string.data["zhCN"]["universal_spell"] = {
    ['"Plucky" Resumes Chicken Form']={t=1000,icon='Ability_Racial_BearForm'},
    ['Aqual Quintessence - Dowse Molten Core Rune']={t=1000,icon='Temp'},
    ['Archaedas Awaken Visual']={t=1500,icon='Spell_Nature_Earthquake'},
    ['Arugal spawn-in spell']={t=2000,icon='Temp'},
    ['Atal\'ai Altar Light Visual']={t=1000,icon='Temp'},
    ['Blue Dragon Transform DND']={t=1000,icon='Temp'},
    ['Brood of Nozdormu Factoin +1000']={t=1000,icon='Temp'},
    ['CHU\'s QUEST SPELL']={t=4000,icon='Spell_Shadow_LifeDrain'},
    ['Conjure Furis Felsteed DUMMY DND']={t=5000,icon='Temp'},
    ['Create Item Visual (DND)']={t=5000,icon='Spell_Shadow_SoulGem'},
    ['CreatureSpecial']={t=2000,icon='Temp'},
    ['Delete Me']={t=4000,icon='INV_Scroll_02'},
    ['Dummy NPC Summon']={t=20000,icon='Spell_Shadow_UnsummonBuilding'},
    ['Editor Test Spell']={t=250,icon='Temp'},
    ['Eye of Yesmur (PT)']={t=2000,icon='Temp'},
    ['Fix Ritual Bell (DND)']={t=3000,icon='Temp'},
    ['Fix Ritual Candle (DND)']={t=3000,icon='Temp'},
    ['Fix Ritual Node (DND)']={t=3000,icon='Temp'},
    ['Form of the Moonstalker (no invis)']={t=1000,icon='Ability_Hibernation'},
    ['Green Dragon Transform DND']={t=1000,icon='Temp'},
    ['Heal Visual']={t=3500,icon='Spell_Holy_Heal'},
    ['Heart of Hakkar - Molthor chucks the heart']={t=2000,icon='Temp'},
    ['Imbue Chest - Absorb']={t=5000,icon='Spell_Holy_GreaterHeal'},
    ['Imbue Chest - Lesser Absorb']={t=5000,icon='Spell_Holy_GreaterHeal'},
    ['Imbue Chest - Minor Spirit']={t=5000,icon='Spell_Holy_GreaterHeal'},
    ['Imbue Cloak - Minor Resistance']={t=5000,icon='Spell_Holy_GreaterHeal'},
    ['Instill Lord Valthalak\'s Spirit DND']={t=5000,icon='Temp'},
    ['Invis Placing Bear Trap']={t=2000,icon='Temp'},
    ['Ivus Teleport Visual DND']={t=1000,icon='Temp'},
    ['J\'eevee summons object']={t=2000,icon='Temp'},
    ['Kev']={t=3000,icon='Spell_Fire_FireBolt'},
    ['Majordomo Teleport Visual']={t=1000,icon='Spell_Arcane_Blink'},
    ['Nefarius Attack 001']={t=1000,icon='Temp'},
    ['New Magic Missile (Test)']={t=2000,icon='Temp'},
    ['Opening - No Text']={t=5000,icon='Temp'},
    ['Ouro Submerge Visual']={t=1500,icon='Spell_Fire_Volcano'},
    ['Pickpocket (PT)']={t=5000,icon='Temp'},
    ['Quest - Sergra Darkthorn Spell']={t=3000,icon='Temp'},
    ['Quest - Teleport Spawn-out']={t=1000,icon='Temp'},
    ['Quest - Troll Hero Summon Visual']={t=30000,icon='Temp'},
    ['Red Dragon Transform DND']={t=1000,icon='Temp'},
    ['Reputation - Ahn\'Qiraj Temple Boss']={t=1000,icon='Temp'},
    ['Rimblat Grows Flower DND']={t=2000,icon='Temp'},
    ['Rookery Whelp Spawn-in Spell']={t=500,icon='Temp'},
    ['Rotate Trigger']={t=3000,icon='Temp'},
    ['Ruul Snowhoof Shapechange (DND)']={t=1000,icon='Temp'},
    ['Sapphiron DND']={t=20000,icon='Temp'},
    ['Sol H']={t=3000,icon='Spell_Frost_ManaRecharge'},
    ['Sol L']={t=3000,icon='Spell_Frost_ManaRecharge'},
    ['Sol M']={t=3000,icon='Spell_Frost_ManaRecharge'},
    ['Sol U']={t=3000,icon='Spell_Frost_ManaRecharge'},
    ['Spawn Challenge to Urok']={t=2000,icon='Temp'},
    ['Spirit Spawn-out']={t=500,icon='Temp'},
    ['Stone Dwarf Awaken Visual']={t=1500,icon='Spell_Nature_Earthquake'},
    ['Stoned - Channel Cast Visual']={t=3000,icon='Spell_Nature_Cyclone'},
    ['Submerge Visual']={t=1500,icon='Spell_Fire_Volcano'},
    ['Summon Thelrin DND']={t=1000,icon='Temp'},
    ['Summon Treasure Horde Visual']={t=1500,icon='Temp'},
    ['Syndicate Tracker (MURP) DND']={t=1000,icon='Spell_Arcane_Blink'},
    ['Teleport to Darnassus - Event']={t=1000,icon='Temp'},
    ['Tell Joke']={t=2000,icon='Spell_Shadow_LifeDrain'},
    ['Test Sharpen Blade']={t=3000,icon='Temp'},
    ['Tharnariun Cure 1']={t=750,icon='Spell_Nature_RemoveDisease'},
    ['Time Stop Visual DND']={t=3000,icon='Temp'},
    ['Uldaman Boss Agro']={t=5000,icon='Spell_Nature_EarthBindTotem'},
    ['Uldaman Sub-Boss Agro']={t=5000,icon='Spell_Nature_EarthBindTotem'},
    ['Viewing Room Student Transform - Effect']={t=1000,icon='Temp'},
    ['Vipore Cat Form DND']={t=1000,icon='Temp'},
    ['Windsor Death DND']={t=1500,icon='Temp'},
    ['Windsor Reading Tablets DND']={t=10000,icon='Temp'},
    ['[PH] Buttress Activator']={t=5000,icon='Temp'},
    ['[PH] Cystal Bazooka']={t=1000,icon='Temp'},
    ['[PH] Teleport to Auberdine']={t=2000,icon='Temp'},
    ['[PH] Teleport to Balthule']={t=2000,icon='Temp'},
    ['[PH] Teleport to Booty Bay']={t=2000,icon='Temp'},
    ['[PH] Teleport to Felwood']={t=2000,icon='Temp'},
    ['[PH] Teleport to Grom\'Gol']={t=2000,icon='Temp'},
    ['[PH] Teleport to Menethil Harbor']={t=2000,icon='Temp'},
    ['[PH] Teleport to Orgrimmar']={t=2000,icon='Temp'},
    ['[PH] Teleport to Ratchet']={t=2000,icon='Temp'},
    ['[PH] Teleport to Theramore']={t=2000,icon='Temp'},
    ['[PH] Teleport to Undercity']={t=2000,icon='Temp'},
    ['不稳定化合物']={t=3000,icon='Spell_Fire_Incinerate'},
    ['与头颅交谈']={t=5000,icon='Spell_Shadow_LifeDrain'},
    ['专注']={t=5000,icon='Temp'},
    ['丘比特之箭']={t=1000,icon='Temp'},
    ['乌洛克爪牙消失']={t=2000,icon='Temp'},
    ['乌瑟尔的祭品']={t=2000,icon='Temp'},
    ['乱射']={t=3000,icon='Ability_TheBlackArrow'},
    ['乱射 II']={t=3000,icon='Ability_TheBlackArrow'},
    ['五月柱']={t=10000,icon='Spell_Shadow_Twilight'},
    ['亚科纳琳之力']={t=4000,icon='Spell_Nature_AstralRecal'},
    ['亚雷戈斯的复仇']={t=2000,icon='Temp'},
    ['从艾萨拉之塔传送']={t=1000,icon='Spell_Nature_EarthBind'},
    ['仲夏腊肠']={t=1000,icon='INV_Misc_Food_53'},
    ['伊克鲁德的守护者']={t=5000,icon='Spell_Shadow_SummonVoidWalker'},
    ['伊莫塔尔之眼']={t=2000,icon='Spell_Shadow_AntiMagicShell'},
    ['伊鲁克斯之手']={t=5000,icon='Temp'},
    ['伐木机高温喷射']={t=2000,icon='Spell_Fire_Incinerate'},
    ['休眠']={t=1500,icon='Spell_Nature_Sleep'},
    ['传授末日咆哮']={t=1000,icon='Temp'},
    ['传送']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
    ['传送到海潮祭坛']={t=2000,icon='Temp'},
    ['传送到艾萨拉之塔']={t=1000,icon='Spell_Nature_AstralRecalGroup'},
    ['传送门：卡拉赞']={t=10000,icon='Spell_Arcane_PortalUnderCity'},
    ['传送门：奥格瑞玛']={t=10000,icon='Spell_Arcane_PortalOrgrimmar'},
    ['传送门：幽暗城']={t=10000,icon='Spell_Arcane_PortalUnderCity'},
    ['传送门：暴风城']={t=10000,icon='Spell_Arcane_PortalStormWind'},
    ['传送门：达纳苏斯']={t=10000,icon='Spell_Arcane_PortalDarnassus'},
    ['传送门：铁炉堡']={t=10000,icon='Spell_Arcane_PortalIronForge'},
    ['传送门：雷霆崖']={t=10000,icon='Spell_Arcane_PortalThunderBluff'},
    ['传送：修道院']={t=2000,icon='Temp'},
    ['传送：兵营']={t=2000,icon='Temp'},
    ['传送：北郡修道院']={t=2000,icon='Temp'},
    ['传送：墓地']={t=2000,icon='Temp'},
    ['传送：夜色镇']={t=2000,icon='Temp'},
    ['传送：奥格瑞玛']={t=10000,icon='Spell_Arcane_TeleportOrgrimmar'},
    ['传送：安威玛尔']={t=2000,icon='Temp'},
    ['传送：幽暗城']={t=10000,icon='Spell_Arcane_TeleportUnderCity'},
    ['传送：暮色森林']={t=2000,icon='Temp'},
    ['传送：暴风城']={t=10000,icon='Spell_Arcane_TeleportStormWind'},
    ['传送：月光林地']={t=10000,icon='Spell_Arcane_TeleportMoonglade'},
    ['传送：月溪镇']={t=2000,icon='Temp'},
    ['传送：树人']={t=2000,icon='Temp'},
    ['传送：灯塔']={t=2000,icon='Temp'},
    ['传送：艾尔文森林']={t=2000,icon='Temp'},
    ['传送：西部荒野']={t=2000,icon='Temp'},
    ['传送：达纳苏斯']={t=10000,icon='Spell_Arcane_TeleportDarnassus'},
    ['传送：铁炉堡']={t=10000,icon='Spell_Arcane_TeleportIronForge'},
    ['传送：闪金镇']={t=2000,icon='Temp'},
    ['传送：雷霆崖']={t=10000,icon='Spell_Arcane_TeleportThunderBluff'},
    ['伤害增效']={t=2000,icon='Spell_Nature_AbolishMagic'},
    ['伤害车辆']={t=2000,icon='Spell_Fire_Fire'},
    ['低沉咆哮']={t=1500,icon='Spell_Fire_Fire'},
    ['作呕瘟疫']={t=2000,icon='Spell_Shadow_CallofBone'},
    ['佯射']={t=2000,icon='Ability_Marksmanship'},
    ['使用灵珠']={t=3000,icon='Temp'},
    ['使用药膏']={t=1300,icon='Temp'},
    ['使用诱引激素']={t=2500,icon='INV_Misc_Bowl_01'},
    ['侏儒传送器']={t=10000,icon='Temp'},
    ['侏儒摄像头连接']={t=3000,icon='Temp'},
    ['修理塔瓦斯德的项链']={t=4500,icon='Spell_Holy_Restoration'},
    ['假人轰炸']={t=2000,icon='Temp'},
    ['催眠曲']={t=1000,icon='Spell_Shadow_SoothingKiss'},
    ['催眠术']={t=1500,icon='Spell_Nature_Sleep'},
    ['元素之怒']={t=1000,icon='Spell_Fire_FireArmor'},
    ['元素护甲']={t=1000,icon='Spell_Frost_Frost'},
    ['元素火焰']={t=500,icon='Spell_Fire_Fireball02'},
    ['充实']={t=500,icon='Spell_Shadow_Charm'},
    ['充电网']={t=500,icon='Ability_Ensnare'},
    ['充能']={t=5000,icon='Spell_Shadow_EvilEye'},
    ['充能奥术箭']={t=7000,icon='Spell_Arcane_StarFire'},
    ['先祖之魂']={t=10000,icon='Spell_Nature_Regenerate'},
    ['光明之泉']={t=1500,icon='Spell_Holy_SummonLightwell'},
    ['光明屏障']={t=2000,icon='Temp'},
    ['光明美味朗姆酒']={t=1000,icon='INV_Drink_08'},
    ['克隆']={t=2500,icon='Spell_Shadow_BlackPlague'},
    ['克雷格的烈酒']={t=1000,icon='INV_Drink_05'},
    ['全效治疗']={t=1000,icon='Temp'},
    ['公主召唤传送门']={t=10000,icon='Spell_Arcane_PortalIronForge'},
    ['共同禁锢']={t=1500,icon='Spell_Shadow_UnsummonBuilding'},
    ['关闭']={t=1000,icon='Temp'},
    ['内爆']={t=10000,icon='Spell_Fire_SelfDestruct'},
    ['农夫伪装']={t=3000,icon='Ability_Rogue_Disguise'},
    ['冬泉霜刃豹']={t=3000,icon='Ability_Mount_PinkTiger'},
    ['冬狼']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
    ['冰冻术']={t=4000,icon='Spell_Frost_Glacier'},
    ['冰冻龙蛋']={t=500,icon='Temp'},
    ['冰冻龙蛋 - 初号机']={t=500,icon='Temp'},
    ['冰息术']={t=1000,icon='Spell_Frost_Wisp'},
    ['冰斧智慧']={t=1000,icon='Ability_Ambush'},
    ['冰柱']={t=1500,icon='Spell_Frost_FrostBolt02'},
    ['冰蓝色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['冰链术']={t=1300,icon='Spell_Frost_ChainsOfIce'},
    ['冰霜之油']={t=3000,icon='Temp'},
    ['冰霜凝固']={t=2500,icon='Spell_Frost_Glacier'},
    ['冰霜抗性']={t=1000,icon='Spell_Frost_WizardMark'},
    ['冰霜灼烧']={t=2000,icon='Spell_Frost_ChillingBlast'},
    ['冰霜虚弱']={t=5000,icon='INV_Misc_QirajiCrystal_04'},
    ['净化元素之灵']={t=4000,icon='Temp'},
    ['净化冰蹄水井']={t=10000,icon='Temp'},
    ['净化并放置食物']={t=5000,icon='INV_Misc_Bowl_01'},
    ['净化臭气弹']={t=5000,icon='Temp'},
    ['净化蛮鬃水井']={t=10000,icon='Temp'},
    ['净化雷角水井']={t=10000,icon='Temp'},
    ['凋零之触']={t=2000,icon='Spell_Nature_Drowsy'},
    ['减速毒药']={t=1000,icon='Spell_Nature_SlowPoison'},
    ['减速毒药 II']={t=1000,icon='Spell_Nature_SlowPoison'},
    ['出生']={t=2000,icon='Temp'},
    ['击碎']={t=5000,icon='Temp'},
    ['分解']={t=3000,icon='Spell_Holy_RemoveCurse'},
    ['创造占卜之碗']={t=2500,icon='INV_Misc_Bowl_01'},
    ['初级巫师之油']={t=3000,icon='Temp'},
    ['初级法力之油']={t=3000,icon='Temp'},
    ['制造PX83型密码机']={t=2000,icon='INV_Misc_Bowl_01'},
    ['制造伐木机']={t=1000,icon='INV_Misc_Gear_01'},
    ['制造先知之水']={t=5000,icon='Spell_Shadow_LifeDrain'},
    ['制造净化图腾']={t=5000,icon='Spell_Shadow_LifeDrain'},
    ['制造初级治疗石']={t=3000,icon='INV_Stone_04'},
    ['制造卷轴']={t=5000,icon='INV_Scroll_05'},
    ['制造召唤法阵']={t=10000,icon='Temp'},
    ['制造召集法阵']={t=10000,icon='Temp'},
    ['制造封灵箱']={t=500,icon='Temp'},
    ['制造强效治疗石']={t=3000,icon='INV_Stone_04'},
    ['制造枯木图腾束']={t=2000,icon='Spell_Lightning_LightningBolt01'},
    ['制造次级治疗石']={t=3000,icon='INV_Stone_04'},
    ['制造治疗石']={t=3000,icon='INV_Stone_04'},
    ['制造法师的宝珠']={t=4000,icon='Temp'},
    ['制造法师的长袍']={t=4000,icon='Temp'},
    ['制造灵契']={t=3000,icon='INV_Misc_Food_09'},
    ['制造烟花发射器']={t=2000,icon='INV_Musket_04'},
    ['制造烟花束发射器']={t=2000,icon='INV_Misc_EngGizmos_03'},
    ['制造特效治疗石']={t=3000,icon='INV_Stone_04'},
    ['制造裂隙']={t=3000,icon='Temp'},
    ['制造装满的封灵箱']={t=2000,icon='Temp'},
    ['制造遗物包裹']={t=1000,icon='Temp'},
    ['刺骨暗影']={t=2000,icon='Spell_Shadow_ChillTouch'},
    ['剃刀之鬃']={t=1000,icon='Spell_Nature_Thorns'},
    ['削弱']={t=2000,icon='Spell_Shadow_CurseOfMannoroth'},
    ['剥皮']={t=2000,icon='INV_Misc_Pelt_Wolf_01'},
    ['剧烈痛楚']={t=1000,icon='Spell_Shadow_ShadowWordPain'},
    ['力量衰减']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
    ['加卡尔的翻译']={t=4500,icon='Spell_Holy_Restoration'},
    ['劣质炸药']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['劣质铜壳炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['包围之风']={t=2000,icon='Spell_Nature_Cyclone'},
    ['区域燃烧']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['千刃']={t=250,icon='INV-Sword_53'},
    ['卓越巫师之油']={t=3000,icon='Temp'},
    ['卓越法力之油']={t=3000,icon='Temp'},
    ['南海海盗伪装']={t=3000,icon='Ability_Rogue_Disguise'},
    ['南海火炮开火']={t=5000,icon='Spell_Fire_FireBolt02'},
    ['占卜沉思']={t=5000,icon='Temp'},
    ['卡德加开锁术']={t=10000,icon='INV_Misc_Key_14'},
    ['卡德拉克的旗子']={t=2000,icon='INV_Banner_03'},
    ['卡拉然合成火炬']={t=1000,icon='Temp'},
    ['卡死']={t=10000,icon='Spell_Shadow_Teleport'},
    ['叉状闪电']={t=2000,icon='Spell_Nature_ChainLightning'},
    ['反手一击']={t=1000,icon='Spell_Shadow_LifeDrain'},
    ['反转之盾']={t=1000,icon='Spell_Shadow_Teleport'},
    ['反魔法盾']={t=2000,icon='Spell_Shadow_AntiMagicShell'},
    ['发射导弹']={t=3000,icon='INV_Ammo_Bullet_03'},
    ['发射火箭']={t=3000,icon='INV_Ammo_Bullet_03'},
    ['变形受害者']={t=2000,icon='Spell_Magic_LesserInvisibilty'},
    ['变形术']={t=1500,icon='Spell_Nature_Polymorph'},
    ['变形术：奶牛']={t=1500,icon='Spell_Nature_Polymorph_Cow'},
    ['变形术：猪']={t=1500,icon='Spell_Magic_PolymorphPig'},
    ['变形术：龟']={t=1500,icon='Ability_Hunter_Pet_Turtle'},
    ['古神之力']={t=2000,icon='Spell_Shadow_Requiem'},
    ['召唤']={t=1000,icon='Spell_Arcane_Blink'},
    ['召唤上古之魂']={t=4000,icon='Spell_Nature_Purge'},
    ['召唤上古力量']={t=7000,icon='Temp'},
    ['召唤乌洛克']={t=1000,icon='Temp'},
    ['召唤亚奎门塔斯']={t=2000,icon='Temp'},
    ['召唤仪式']={t=5000,icon='Spell_Shadow_Twilight'},
    ['召唤仪式效果']={t=5000,icon='Temp'},
    ['召唤伊弗斯']={t=10000,icon='Temp'},
    ['召唤伊沙姆哈尔']={t=2000,icon='Spell_Shadow_LifeDrain'},
    ['召唤僵尸']={t=2000,icon='Spell_Shadow_RaiseDead'},
    ['召唤克索诺斯恐惧战马']={t=5000,icon='Temp'},
    ['召唤冈瑟尔的幻影']={t=2000,icon='Temp'},
    ['召唤军马']={t=3000,icon='Spell_Nature_Swiftness'},
    ['召唤农场小鸡']={t=1000,icon='Ability_Seal'},
    ['召唤加布林']={t=1000,icon='Ability_Seal'},
    ['召唤卡拉恩的旗子']={t=500,icon='Temp'},
    ['召唤古树之魂']={t=2000,icon='Temp'},
    ['召唤咒逐']={t=1000,icon='Temp'},
    ['召唤咕唧']={t=1000,icon='Ability_Seal'},
    ['召唤哼哼先生']={t=1000,icon='Ability_Seal'},
    ['召唤圆头钳嘴龟']={t=1000,icon='Ability_Seal'},
    ['召唤土拨鼠']={t=1000,icon='Ability_Seal'},
    ['召唤地狱战马']={t=3000,icon='Spell_Nature_Swiftness'},
    ['召唤地狱火仆从']={t=2000,icon='Spell_Shadow_SummonInfernal'},
    ['召唤地狱猎犬']={t=10000,icon='Spell_Shadow_SummonFelHunter'},
    ['召唤地精炸弹']={t=250,icon='Ability_Repair'},
    ['召唤地鼠']={t=2000,icon='Spell_Nature_ProtectionformNature'},
    ['召唤埃其亚基']={t=500,icon='Spell_Shadow_LifeDrain'},
    ['召唤塔吉']={t=1000,icon='Ability_Seal'},
    ['召唤塞克隆尼亚']={t=10000,icon='Spell_Nature_EarthBind'},
    ['召唤复活的侍从']={t=2000,icon='Spell_Shadow_RaiseDead'},
    ['召唤奥妮克希亚雏龙']={t=2000,icon='Temp'},
    ['召唤孤儿']={t=1000,icon='Ability_Seal'},
    ['召唤安静的机械雪人']={t=1000,icon='Ability_Seal'},
    ['召唤宝珠恶魔']={t=5000,icon='Temp'},
    ['召唤密斯莱尔']={t=10000,icon='Spell_Shadow_LifeDrain'},
    ['召唤寻宝部落']={t=1500,icon='Temp'},
    ['召唤小精灵']={t=1000,icon='Ability_Seal'},
    ['召唤小老鼠']={t=1000,icon='Ability_Seal'},
    ['召唤小鬼']={t=10000,icon='Spell_Shadow_SummonImp'},
    ['召唤小鱼人']={t=1000,icon='Ability_Seal'},
    ['召唤尖啸者的灵魂']={t=2000,icon='Temp'},
    ['召唤屏障']={t=10000,icon='Temp'},
    ['召唤岛蛙']={t=1000,icon='Ability_Seal'},
    ['召唤希洛塔姆']={t=2500,icon='Temp'},
    ['召唤幻影怨灵']={t=1000,icon='Spell_Shadow_Teleport'},
    ['召唤幻影梦魇兽']={t=2000,icon='Spell_Fire_SealOfFire'},
    ['召唤幻象之影']={t=2000,icon='Spell_Fire_SealOfFire'},
    ['召唤座狼幼崽']={t=1000,icon='Ability_Seal'},
    ['召唤恐惧战马']={t=3000,icon='Ability_Mount_Dreadsteed'},
    ['召唤恶心的软泥怪']={t=1000,icon='Ability_Seal'},
    ['召唤战马']={t=3000,icon='Ability_Mount_Charger'},
    ['召唤报警机器人']={t=250,icon='INV_Gizmo_08'},
    ['召唤拉格纳罗斯']={t=10000,icon='Spell_Fire_LavaSpawn'},
    ['召唤拉瑟莱克']={t=10000,icon='Temp'},
    ['召唤持盾守卫']={t=5000,icon='Spell_Nature_Purge'},
    ['召唤效果']={t=5000,icon='Spell_Shadow_AnimateDead'},
    ['召唤斑点兔']={t=1000,icon='Ability_Seal'},
    ['召唤普通猫']={t=2000,icon='INV_Box_PetCarrier_01'},
    ['召唤暗影之击']={t=10000,icon='Temp'},
    ['召唤暗影法师']={t=5000,icon='Spell_Shadow_RaiseDead'},
    ['召唤暗牙恐狼']={t=1300,icon='Spell_Shadow_ChillTouch'},
    ['召唤月爪枭兽']={t=3000,icon='Temp'},
    ['召唤机器人']={t=1000,icon='Ability_Seal'},
    ['召唤机械小鸡']={t=1000,icon='Ability_Seal'},
    ['召唤林精']={t=3000,icon='Spell_Nature_ProtectionformNature'},
    ['召唤林蛙']={t=1000,icon='Ability_Seal'},
    ['召唤枯木地狱猎犬']={t=3000,icon='Spell_Shadow_SummonFelHunter'},
    ['召唤树人']={t=1500,icon='Spell_Nature_ForceOfNature'},
    ['召唤树蛙']={t=1000,icon='Ability_Seal'},
    ['召唤梦境裂隙']={t=10000,icon='Temp'},
    ['召唤棕色猫头鹰']={t=1000,icon='Ability_Seal'},
    ['召唤棕色蟒蛇']={t=1000,icon='Ability_Seal'},
    ['召唤毒蛇']={t=1500,icon='Spell_Nature_ResistMagic'},
    ['召唤水元素']={t=2000,icon='Spell_Shadow_SealOfKings'},
    ['召唤沼泽幽魂']={t=1500,icon='Spell_Nature_AbolishMagic'},
    ['召唤沼泽淤泥怪']={t=2500,icon='Spell_Shadow_BlackPlague'},
    ['召唤法师']={t=5000,icon='Spell_Nature_Purge'},
    ['召唤法术卫兵']={t=5000,icon='Spell_Nature_Purge'},
    ['召唤法杖']={t=2000,icon='INV_Staff_26'},
    ['召唤波利']={t=1000,icon='Ability_Seal'},
    ['召唤活火']={t=2000,icon='Spell_Fire_Fire'},
    ['召唤灰烬']={t=2000,icon='Spell_Fire_Fire'},
    ['召唤灰猫']={t=1000,icon='Ability_Seal'},
    ['召唤灰色小鸡']={t=1000,icon='Ability_Seal'},
    ['召唤灰色座狼']={t=1300,icon='Spell_Shadow_ChillTouch'},
    ['召唤炸弹']={t=1000,icon='Ability_Seal'},
    ['召唤烟网蜘蛛']={t=1000,icon='Ability_Seal'},
    ['召唤熊猫']={t=1000,icon='Ability_Seal'},
    ['召唤爪牙']={t=500,icon='Temp'},
    ['召唤特沃什的爪牙']={t=4000,icon='Spell_Frost_Wisp'},
    ['召唤狮鹫坐骑']={t=3000,icon='Ability_BullRush'},
    ['召唤玛格拉姆劫掠者']={t=4000,icon='Spell_Shadow_RaiseDead'},
    ['召唤白猫']={t=1000,icon='Ability_Seal'},
    ['召唤白色小鸡']={t=1000,icon='Ability_Seal'},
    ['召唤白色猫头鹰']={t=1000,icon='Ability_Seal'},
    ['召唤白色虎崽']={t=1000,icon='Ability_Seal'},
    ['召唤白色钳嘴龟']={t=1000,icon='Ability_Seal'},
    ['召唤白鳞蛇']={t=1000,icon='Ability_Seal'},
    ['召唤睡梦守卫的幻象']={t=1000,icon='Spell_Shadow_Teleport'},
    ['召唤石翼石像鬼']={t=10000,icon='Spell_Shadow_UnsummonBuilding'},
    ['召唤硬皮钳嘴龟']={t=1000,icon='Ability_Seal'},
    ['召唤碎腭']={t=3000,icon='Temp'},
    ['召唤祈福']={t=1000,icon='Temp'},
    ['召唤精灵龙宝宝']={t=1000,icon='Ability_Seal'},
    ['召唤精龙宝宝']={t=1000,icon='Ability_Seal'},
    ['召唤红尾鹦鹉']={t=1000,icon='Ability_Seal'},
    ['召唤红色其拉作战坦克']={t=3000,icon='INV_Misc_QirajiCrystal_02'},
    ['召唤红色小神龙']={t=1000,icon='Ability_Seal'},
    ['召唤红鹦鹉']={t=1000,icon='Ability_Seal'},
    ['召唤红龙宝宝']={t=1000,icon='Ability_Seal'},
    ['召唤结界雕文']={t=3000,icon='Temp'},
    ['召唤绿翼鹦鹉']={t=1000,icon='Ability_Seal'},
    ['召唤绿色其拉作战坦克']={t=3000,icon='INV_Misc_QirajiCrystal_03'},
    ['召唤绿色小神龙']={t=1000,icon='Ability_Seal'},
    ['召唤绿色水蛇']={t=1000,icon='Ability_Seal'},
    ['召唤绿色钳嘴龟']={t=1000,icon='Ability_Seal'},
    ['召唤绿龙宝宝']={t=1000,icon='Ability_Seal'},
    ['召唤美冠鹦鹉']={t=1000,icon='Ability_Seal'},
    ['召唤群居雏龙']={t=2000,icon='Temp'},
    ['召唤脆弱的骷髅']={t=10000,icon='Spell_Shadow_RaiseDead'},
    ['召唤腐化猫']={t=1000,icon='Ability_Seal'},
    ['召唤腐食甲虫']={t=2000,icon='Spell_Shadow_CarrionSwarm'},
    ['召唤艾丹娜·邪爪']={t=4000,icon='Temp'},
    ['召唤花羽鹦鹉']={t=1000,icon='Ability_Seal'},
    ['召唤蓝色其拉作战坦克']={t=3000,icon='INV_Misc_QirajiCrystal_04'},
    ['召唤蓝蛙']={t=1000,icon='Ability_Seal'},
    ['召唤蓝鳞蛇']={t=1000,icon='Ability_Seal'},
    ['召唤蓝龙宝宝']={t=1000,icon='Ability_Seal'},
    ['召唤虎皮猫']={t=1000,icon='Ability_Seal'},
    ['召唤虚无行者']={t=4000,icon='Spell_Shadow_GatherShadows'},
    ['召唤虚空行者']={t=10000,icon='Spell_Shadow_SummonVoidWalker'},
    ['召唤蜘蛛之神']={t=10000,icon='Spell_Shadow_LifeDrain'},
    ['召唤蟑螂']={t=1000,icon='Ability_Seal'},
    ['召唤血瓣花瘟疫']={t=2000,icon='Spell_Shadow_DarkSummoning'},
    ['召唤血纹蛇']={t=1000,icon='Ability_Seal'},
    ['召唤被奴役的座狼']={t=1300,icon='Spell_Shadow_ChillTouch'},
    ['召唤角鹰兽宝宝']={t=1000,icon='Ability_Seal'},
    ['召唤贝尔加的产物']={t=4000,icon='Spell_Fire_LavaSpawn'},
    ['召唤赤环蛇']={t=1000,icon='Ability_Seal'},
    ['召唤赤练蛇']={t=1000,icon='Ability_Seal'},
    ['召唤赫尔库拉之犬']={t=3000,icon='Spell_Shadow_Haunting'},
    ['召唤跳跳虫']={t=1000,icon='Ability_Seal'},
    ['召唤辛迪加鬼魂']={t=1000,icon='Spell_Shadow_Twilight'},
    ['召唤达古恩']={t=5000,icon='Temp'},
    ['召唤迷你破坏神']={t=1000,icon='Ability_Seal'},
    ['召唤逼真的蟾蜍']={t=1000,icon='Ability_Seal'},
    ['召唤遥控傀儡']={t=3000,icon='Ability_Repair'},
    ['召唤野猪之魂']={t=1500,icon='Spell_Magic_PolymorphPig'},
    ['召唤金翼鹦鹉']={t=1000,icon='Ability_Seal'},
    ['召唤错觉狼影']={t=1000,icon='Spell_Shadow_Teleport'},
    ['召唤阿塔莱骷髅']={t=1000,icon='Spell_Shadow_RaiseDead'},
    ['召唤阿里亚']={t=2500,icon='Spell_Nature_GroundingTotem'},
    ['召唤雷霆之击']={t=10000,icon='Temp'},
    ['召唤青铜龙宝宝']={t=1000,icon='Ability_Seal'},
    ['召唤飞毛腿']={t=1000,icon='Ability_Seal'},
    ['召唤骷髅']={t=2000,icon='Spell_Shadow_RaiseDead'},
    ['召唤魅魔']={t=10000,icon='Spell_Shadow_SummonSuccubus'},
    ['召唤鲨鱼宝宝']={t=1000,icon='Ability_Seal'},
    ['召唤鹰喙钳嘴龟']={t=1000,icon='Ability_Seal'},
    ['召唤黄毛兔']={t=1000,icon='Ability_Seal'},
    ['召唤黄猫']={t=1000,icon='Ability_Seal'},
    ['召唤黄纹兔']={t=1000,icon='Ability_Seal'},
    ['召唤黄色其拉作战坦克']={t=3000,icon='INV_Misc_QirajiCrystal_01'},
    ['召唤黄色猫头鹰']={t=1000,icon='Ability_Seal'},
    ['召唤黑尾白猫']={t=1000,icon='Ability_Seal'},
    ['召唤黑手恐法师']={t=5000,icon='Spell_Nature_Purge'},
    ['召唤黑手老兵']={t=5000,icon='Spell_Nature_Purge'},
    ['召唤黑斑白猫']={t=1000,icon='Ability_Seal'},
    ['召唤黑纹灰猫']={t=1000,icon='Ability_Seal'},
    ['召唤黑色其拉作战坦克']={t=3000,icon='INV_Misc_QirajiCrystal_05'},
    ['召唤黑色猫头鹰']={t=1000,icon='Ability_Seal'},
    ['召唤黑色王蛇']={t=1000,icon='Ability_Seal'},
    ['召唤黑龙宝宝']={t=1000,icon='Ability_Seal'},
    ['召回']={t=10000,icon='Temp'},
    ['合并火炬']={t=5000,icon='Temp'},
    ['吐息']={t=5000,icon='Spell_Fire_Fire'},
    ['吞噬之影']={t=1500,icon='Spell_Shadow_LifeDrain02'},
    ['含毒喷溅']={t=2000,icon='Spell_Nature_CorrosiveBreath'},
    ['启迪']={t=2000,icon='Spell_Shadow_Fumble'},
    ['哈卡的诅咒']={t=2500,icon='Spell_Shadow_GatherShadows'},
    ['哈卡酸液']={t=1000,icon='Spell_Nature_Acid_01'},
    ['唤醒克罗尼亚']={t=4500,icon='Temp'},
    ['唤醒地灵宝库守卫']={t=5000,icon='Spell_Nature_Earthquake'},
    ['唤醒夺魂者']={t=5000,icon='Temp'},
    ['喝下初级药水']={t=3000,icon='Spell_Holy_Heal'},
    ['喝药水']={t=3000,icon='Spell_Holy_Heal'},
    ['嚎叫之怒']={t=5000,icon='Ability_BullRush'},
    ['图勒之怒']={t=1500,icon='Spell_Shadow_UnholyFrenzy'},
    ['图勒的诅咒']={t=2000,icon='Spell_Shadow_ShadowPact'},
    ['土元素']={t=3000,icon='Ability_Temp'},
    ['圣光击']={t=2500,icon='Spell_Holy_HolySmite'},
    ['圣光术']={t=2500,icon='Spell_Holy_HolyBolt'},
    ['圣光闪现']={t=1500,icon='Spell_Holy_FlashHeal'},
    ['地狱火']={t=2000,icon='Spell_Shadow_SummonInfernal'},
    ['地狱火罩']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['地狱烈焰']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['地狱烈焰 II']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['地狱烈焰 III']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['地穴甲虫']={t=1500,icon='Spell_Shadow_CarrionSwarm'},
    ['地精摄像头连接']={t=3000,icon='Temp'},
    ['地精暗雷']={t=1000,icon='Spell_Shadow_Metamorphosis'},
    ['地精迫击炮']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['埃提耶什驱魔']={t=20000,icon='Temp'},
    ['埋葬塞缪尔的遗体']={t=2000,icon='Temp'},
    ['基尔罗格之眼']={t=5000,icon='Spell_Shadow_EvilEye'},
    ['基础营火']={t=10000,icon='Spell_Fire_Fire'},
    ['堕落的雷德帕斯']={t=2000,icon='Temp'},
    ['塔姆拉树苗']={t=1300,icon='Temp'},
    ['增强钝器']={t=3000,icon='Temp'},
    ['增强钝器 II']={t=3000,icon='Temp'},
    ['增强钝器 III']={t=3000,icon='Temp'},
    ['增强钝器 IV']={t=3000,icon='Temp'},
    ['增强钝器 V']={t=3000,icon='Temp'},
    ['墨汁喷射']={t=1000,icon='Spell_Nature_Sleep'},
    ['声望 - 加基森 +500']={t=1000,icon='Temp'},
    ['声望 - 棘齿城 +500']={t=1000,icon='Temp'},
    ['声望 - 永望镇 +500']={t=1000,icon='Temp'},
    ['声望 - 藏宝海湾 +500']={t=1000,icon='Temp'},
    ['复活亡灵甲虫']={t=1000,icon='Spell_Shadow_Contagion'},
    ['复活宠物']={t=10000,icon='Ability_Hunter_BeastSoothe'},
    ['复活掘地鼠']={t=3000,icon='Spell_Holy_Resurrection'},
    ['复活术']={t=10000,icon='Spell_Holy_Resurrection'},
    ['复活死者']={t=1000,icon='Spell_Shadow_RaiseDead'},
    ['复生']={t=2000,icon='Spell_Nature_Reincarnation'},
    ['多彩坐骑']={t=3000,icon='INV_Misc_Head_Dragon_Black'},
    ['夜刃豹']={t=3000,icon='Ability_Mount_BlackPanther'},
    ['夜色虫']={t=5000,icon='Trade_Fishing'},
    ['大型爆盐炸弹']={t=5000,icon='Temp'},
    ['大型铜壳炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['大炸弹']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['大规模迫击炮']={t=3000,icon='Temp'},
    ['奇特的朗姆酒']={t=1000,icon='INV_Drink_03'},
    ['奥术炸弹']={t=1500,icon='Spell_Holy_Silence'},
    ['奥术箭']={t=1000,icon='Spell_Arcane_StarFire'},
    ['奥术虚弱']={t=5000,icon='INV_Misc_QirajiCrystal_01'},
    ['奥达曼钥匙法杖']={t=5000,icon='Temp'},
    ['奥金万能钥匙']={t=5000,icon='Temp'},
    ['奥齐爆炸']={t=2000,icon='Temp'},
    ['女妖之嚎']={t=2000,icon='Spell_Shadow_Possession'},
    ['女妖哀嚎']={t=1500,icon='Spell_Shadow_ShadowBolt'},
    ['女妖诅咒']={t=2000,icon='Spell_Nature_Drowsy'},
    ['奴役恶魔']={t=3000,icon='Spell_Shadow_EnslaveDemon'},
    ['奴隶吸取']={t=1000,icon='Spell_Shadow_ChillTouch'},
    ['妖术']={t=2000,icon='Spell_Nature_Polymorph'},
    ['威吓低吼']={t=1000,icon='Ability_Racial_Cannibalize'},
    ['威慑凝视']={t=2000,icon='Spell_Shadow_Charm'},
    ['娜玛拉的爱情药水']={t=1000,icon='Temp'},
    ['安图苏尔的治疗波']={t=1000,icon='Spell_Holy_Heal02'},
    ['安抚动物']={t=1500,icon='Ability_Hunter_BeastSoothe'},
    ['实心炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['宽恕']={t=1000,icon='Temp'},
    ['寄生']={t=2000,icon='Ability_Poisons'},
    ['寒冬']={t=1500,icon='Spell_Nature_NullifyDisease'},
    ['寒冰之墓']={t=1500,icon='Spell_Frost_Glacier'},
    ['寒冰之浪']={t=2000,icon='Spell_Frost_FrostNova'},
    ['寒冰咆哮']={t=1000,icon='Spell_Frost_FrostNova'},
    ['寒冰箭']={t=3000,icon='Spell_Frost_FrostBolt02'},
    ['察觉']={t=1000,icon='Temp'},
    ['寻找遗物碎片']={t=5000,icon='Temp'},
    ['封闭时空裂隙']={t=5000,icon='Temp'},
    ['小型爆盐炸弹']={t=5000,icon='Temp'},
    ['小型青铜炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['尖刺之雨']={t=500,icon='Ability_ImpalingBolt'},
    ['尖锐之矛']={t=500,icon='Ability_ImpalingBolt'},
    ['工兵爆破']={t=5000,icon='Spell_Fire_SelfDestruct'},
    ['巨化术']={t=2000,icon='Spell_Nature_Strength'},
    ['巨型喷泉']={t=1500,icon='Spell_Frost_SummonWaterElemental'},
    ['巫师之油']={t=3000,icon='Temp'},
    ['巫毒']={t=1000,icon='Spell_Shadow_AntiShadow'},
    ['巫毒妖术']={t=1000,icon='Spell_Shadow_CurseOfMannoroth'},
    ['布莱队友逃跑']={t=10000,icon='INV_Misc_Rune_01'},
    ['希斯耐特吸血术']={t=2000,icon='Spell_Shadow_Haunting'},
    ['干扰群居龙蛋']={t=1000,icon='Temp'},
    ['幽魂之狼']={t=3000,icon='Spell_Nature_SpiritWolf'},
    ['开启符文']={t=5000,icon='Temp'},
    ['开锁']={t=5000,icon='Temp'},
    ['异种蝎群瘟疫']={t=2000,icon='Spell_Nature_NullifyDisease'},
    ['弓射击']={t=1000,icon='Ability_Marksmanship'},
    ['弩射击']={t=1000,icon='Ability_Marksmanship'},
    ['弱化']={t=1500,icon='Ability_Creature_Poison_03'},
    ['弱效寒冰箭']={t=2200,icon='Spell_Frost_FrostBolt02'},
    ['强力嗅盐']={t=2000,icon='INV_Misc_Ammo_Gunpowder_01'},
    ['强力爆盐炸弹']={t=5000,icon='Temp'},
    ['强力驱散']={t=4000,icon='Spell_Arcane_StarFire'},
    ['强化宠物']={t=500,icon='Spell_Shadow_DeathPact'},
    ['强效治疗术']={t=3000,icon='Spell_Holy_GreaterHeal'},
    ['强效隐形']={t=3000,icon='Spell_Nature_Invisibilty'},
    ['德鲁伊的睡眠']={t=2500,icon='Spell_Nature_Sleep'},
    ['心灵占卜']={t=5000,icon='Spell_Holy_Restoration'},
    ['心灵腐蚀']={t=2000,icon='Spell_Shadow_MindRot'},
    ['心灵震爆']={t=1500,icon='Spell_Shadow_UnholyFrenzy'},
    ['心灵震颤']={t=2000,icon='Spell_Nature_Earthquake'},
    ['快乐奶油']={t=1000,icon='INV_ValentinesChocolate01'},
    ['快速传染']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
    ['快速冰霜防护结界']={t=1500,icon='Spell_Fire_SealOfFire'},
    ['快速嗜血']={t=2000,icon='Spell_Nature_BloodLust'},
    ['快速治疗']={t=1500,icon='Spell_Holy_FlashHeal'},
    ['快速烈焰防护结界']={t=1500,icon='Spell_Fire_SealOfFire'},
    ['怀旧']={t=4000,icon='Spell_Shadow_LifeDrain'},
    ['急救']={t=3000,icon='Spell_Holy_GreaterHeal'},
    ['恐吓野兽']={t=1500,icon='Ability_Druid_Cower'},
    ['恐怖低吼']={t=1000,icon='Ability_Racial_Cannibalize'},
    ['恐惧嚎叫']={t=2000,icon='Spell_Shadow_DeathScream'},
    ['恐惧术']={t=1500,icon='Spell_Shadow_Possession'},
    ['恢复']={t=2000,icon='Spell_Holy_Renew'},
    ['恶魔之锄']={t=5000,icon='Temp'},
    ['恶魔之门']={t=500,icon='Spell_Arcane_TeleportOrgrimmar'},
    ['恶魔召唤火炬']={t=3000,icon='Temp'},
    ['恶魔诅咒']={t=4000,icon='Temp'},
    ['惊骇之爪']={t=1000,icon='Spell_Shadow_ShadowPact'},
    ['惩击']={t=2500,icon='Spell_Holy_HolySmite'},
    ['惩戒之盾']={t=1000,icon='INV_Shield_19'},
    ['惩戒烈焰']={t=3000,icon='Temp'},
    ['愈合']={t=2000,icon='Spell_Nature_ResistNature'},
    ['愤怒']={t=2000,icon='Spell_Nature_AbolishMagic'},
    ['愤怒之锤']={t=1000,icon='Ability_ThunderClap'},
    ['慢性毒药']={t=2000,icon='Spell_Nature_NullifyPoison'},
    ['慢性毒菌']={t=3000,icon='Spell_Shadow_CreepingPlague'},
    ['憎恶喷吐']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
    ['戈多克之王']={t=1000,icon='INV_Crown_02'},
    ['戈多克绿酒']={t=1000,icon='INV_Drink_03'},
    ['战争践踏']={t=500,icon='Ability_WarStomp'},
    ['打击']={t=2000,icon='Temp'},
    ['打开']={t=5000,icon='Temp'},
    ['打开保险箱']={t=5000,icon='Temp'},
    ['打开古物箱']={t=5000,icon='Temp'},
    ['打开圣甲虫箱']={t=5000,icon='Temp'},
    ['打开大型圣甲虫箱']={t=5000,icon='Temp'},
    ['打开密箱']={t=5000,icon='Temp'},
    ['打开斯坦索姆邮箱']={t=5000,icon='Temp'},
    ['打开本尼迪克的箱子']={t=5000,icon='Temp'},
    ['打开玛雷的脚']={t=5000,icon='Temp'},
    ['打开白蚁桶']={t=5000,icon='Temp'},
    ['打开笼子']={t=5000,icon='Temp'},
    ['打开箱子']={t=5000,icon='Temp'},
    ['打开酒吧的门']={t=5000,icon='Temp'},
    ['打开黑暗守护者宝箱']={t=5000,icon='Temp'},
    ['打磨利刃']={t=3000,icon='Temp'},
    ['打磨利刃 II']={t=3000,icon='Temp'},
    ['打磨利刃 III']={t=3000,icon='Temp'},
    ['打磨利刃 IV']={t=3000,icon='Temp'},
    ['打磨利刃 V']={t=3000,icon='Temp'},
    ['投掷梦魇']={t=2000,icon='Spell_Fire_SelfDestruct'},
    ['投掷泥土']={t=1000,icon='Spell_Nature_Sleep'},
    ['投掷泥浆']={t=1000,icon='Spell_Nature_Sleep'},
    ['投掷火炬']={t=1000,icon='Spell_Fire_Flare'},
    ['投掷炸弹']={t=2000,icon='Spell_Fire_SelfDestruct'},
    ['投掷石块']={t=3000,icon='Ability_GolemStormBolt'},
    ['投掷石块 II']={t=3000,icon='Ability_GolemStormBolt'},
    ['投掷臭气弹']={t=2000,icon='INV_Misc_Bowl_01'},
    ['投掷药水']={t=2000,icon='Spell_Misc_Drink'},
    ['投掷黑铁啤酒']={t=500,icon='Temp'},
    ['投石']={t=2000,icon='Ability_Throw'},
    ['折断胫骨']={t=1500,icon='Temp'},
    ['拉扎什迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['拉格纳罗斯之力']={t=500,icon='Spell_Fire_SelfDestruct'},
    ['拉格纳罗斯显现']={t=2900,icon='Spell_Fire_LavaSpawn'},
    ['指挥地鼠']={t=1500,icon='Spell_Shadow_LifeDrain'},
    ['挖掘石柱']={t=5000,icon='Temp'},
    ['挖掘钴矿']={t=1500,icon='Temp'},
    ['捕捉座狼幼崽']={t=2500,icon='Temp'},
    ['捕捉格拉克']={t=3000,icon='Temp'},
    ['掷斧']={t=1000,icon='INV_Axe_08'},
    ['提米的诅咒']={t=1000,icon='Spell_Shadow_ShadowPact'},
    ['提高声望']={t=1000,icon='Temp'},
    ['插旗子']={t=2300,icon='Temp'},
    ['摧毁帐篷']={t=2500,icon='Temp'},
    ['摧毁幽灵磁铁箱']={t=10000,icon='Temp'},
    ['摧毁蛋']={t=3000,icon='INV_Misc_MonsterClaw_02'},
    ['摩罗加尔附魔']={t=1300,icon='Temp'},
    ['播种']={t=5000,icon='Temp'},
    ['支配']={t=1000,icon='Spell_Shadow_ShadowWordDominate'},
    ['收割蜂群']={t=3000,icon='Spell_Holy_Dizzy'},
    ['收集异种蝎卵']={t=5000,icon='Temp'},
    ['收集放射尘']={t=4000,icon='Temp'},
    ['收集白蚁']={t=5000,icon='Temp'},
    ['收集群居龙蛋']={t=500,icon='Temp'},
    ['放狗']={t=2000,icon='Temp'},
    ['放置剧毒粮草']={t=3000,icon='INV_Cask_01'},
    ['放置古斯的信号灯']={t=5000,icon='Temp'},
    ['放置坠饰']={t=5000,icon='Temp'},
    ['放置奥金鱼漂']={t=2000,icon='Temp'},
    ['放置尼姆布亚的长矛']={t=2000,icon='Temp'},
    ['放置幽灵磁铁']={t=1500,icon='Temp'},
    ['放置戈泰什的头颅']={t=5000,icon='Temp'},
    ['放置捕熊陷阱']={t=2000,icon='Temp'},
    ['放置斯里多尔的信号灯']={t=5000,icon='Temp'},
    ['放置未淬火的剑']={t=1000,icon='Temp'},
    ['放置未铸造的印章']={t=500,icon='Temp'},
    ['放置杰斯托的信号灯']={t=5000,icon='Temp'},
    ['放置水晶球']={t=3000,icon='Temp'},
    ['放置火炬']={t=2300,icon='Temp'},
    ['放置烟鬼的炸药']={t=3000,icon='Temp'},
    ['放置狮肉']={t=2500,icon='INV_Misc_Bowl_01'},
    ['放置穆维里克的信号灯']={t=5000,icon='Temp'},
    ['放置维波里的信号灯']={t=5000,icon='Temp'},
    ['放置艾克曼的信号灯']={t=5000,icon='Temp'},
    ['放置蛇颈龙肉']={t=2500,icon='INV_Misc_Bowl_01'},
    ['放置诱饵']={t=4000,icon='Temp'},
    ['放置雷松的信号灯']={t=5000,icon='Temp'},
    ['放逐术']={t=1500,icon='Spell_Shadow_Cripple'},
    ['放逐水浪流放者']={t=1000,icon='Spell_Shadow_LifeDrain'},
    ['放逐烈焰流放者']={t=1000,icon='Spell_Shadow_LifeDrain'},
    ['放逐雷霆流放者']={t=1000,icon='Spell_Shadow_LifeDrain'},
    ['敏捷衰减']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
    ['救伤']={t=7000,icon='Temp'},
    ['救赎']={t=10000,icon='Spell_Holy_Resurrection'},
    ['敲打祖尔法拉克铜锣']={t=500,icon='Temp'},
    ['斑点霜刃豹']={t=3000,icon='Ability_Mount_WhiteTiger'},
    ['斯塔文的诅咒']={t=1000,icon='Spell_Shadow_ShadowPact'},
    ['旋风倾泻']={t=1500,icon='INV_Spear_05'},
    ['时间停止']={t=3000,icon='Temp'},
    ['时间流逝']={t=2000,icon='Spell_Arcane_PortalOrgrimmar'},
    ['明亮的小珠']={t=5000,icon='INV_Misc_Orb_03'},
    ['明亮篝火']={t=10000,icon='Spell_Fire_Fire'},
    ['昏迷炸弹']={t=2000,icon='Spell_Fire_SelfDestruct'},
    ['星火术']={t=3500,icon='Spell_Arcane_StarFire'},
    ['星界传送']={t=10000,icon='Spell_Nature_AstralRecal'},
    ['显形卷轴']={t=2000,icon='Spell_Magic_LesserInvisibilty'},
    ['显现灵魂']={t=5000,icon='Spell_Totem_WardOfDraining'},
    ['普罗德摩尔的防护']={t=3000,icon='Spell_Holy_BlessingOfProtection'},
    ['暗影之油']={t=3000,icon='Temp'},
    ['暗影之门']={t=1000,icon='Spell_Shadow_SealOfKings'},
    ['暗影传送']={t=250,icon='Spell_Shadow_AntiShadow'},
    ['暗影外壳']={t=1000,icon='Spell_Shadow_AntiShadow'},
    ['暗影抗性']={t=1000,icon='Spell_Frost_WizardMark'},
    ['暗影新星 II']={t=3000,icon='Spell_Shadow_ShadeTrueSight'},
    ['暗影烈焰']={t=2000,icon='Spell_Fire_Incinerate'},
    ['暗影箭']={t=3000,icon='Spell_Shadow_ShadowBolt'},
    ['暗影箭失效']={t=2000,icon='Spell_Shadow_ShadowBolt'},
    ['暗影箭雨']={t=3000,icon='Spell_Shadow_ShadowBolt'},
    ['暗影虚弱']={t=5000,icon='INV_Misc_QirajiCrystal_05'},
    ['暗影迷雾']={t=1500,icon='Spell_Shadow_GatherShadows'},
    ['暗影闪现']={t=500,icon='Spell_Shadow_DetectLesserInvisibility'},
    ['暗棕狼']={t=3000,icon='Ability_Mount_BlackDireWolf'},
    ['暗淡幻象']={t=2000,icon='Spell_Shadow_Fumble'},
    ['暗灰狼']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
    ['暗色湖蘑菇']={t=3000,icon='Spell_Holy_HarmUndeadAura'},
    ['暴风雪']={t=2000,icon='Spell_Frost_IceStorm'},
    ['月光林地邀请']={t=5000,icon='Spell_Arcane_TeleportMoonglade'},
    ['未涂色的机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['末日仪式']={t=10000,icon='Spell_Shadow_AntiMagicShell'},
    ['末日仪式效果']={t=10000,icon='Spell_Arcane_PortalDarnassus'},
    ['朱莉叶的祝福']={t=2000,icon='Spell_Holy_Renew'},
    ['机关枪']={t=500,icon='Ability_Marksmanship'},
    ['机枪']={t=100,icon='INV_Musket_04'},
    ['机械修补包']={t=2000,icon='INV_Gizmo_03'},
    ['机械松鼠']={t=1000,icon='Spell_Shadow_Metamorphosis'},
    ['杂色马']={t=3000,icon='Ability_Mount_RidingHorse'},
    ['束缚亡灵']={t=1500,icon='Spell_Nature_Slow'},
    ['条纹夜刃豹']={t=3000,icon='Ability_Mount_BlackPanther'},
    ['条纹霜刃豹']={t=3000,icon='Ability_Mount_WhiteTiger'},
    ['极地冰狼']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
    ['极性转化']={t=3000,icon='Spell_Nature_Lightning'},
    ['林克的回旋镖']={t=500,icon='INV_Weapon_ShortBlade_10'},
    ['枪械射击']={t=1000,icon='Ability_Marksmanship'},
    ['栗色马']={t=3000,icon='Ability_Mount_RidingHorse'},
    ['格罗姆的祭品']={t=2000,icon='Temp'},
    ['桑德的召唤']={t=1500,icon='Spell_Frost_Wisp'},
    ['棕山羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['棕狼']={t=3000,icon='Ability_Mount_BlackDireWolf'},
    ['棕色科多兽']={t=3000,icon='Ability_Mount_Kodo_03'},
    ['棕色骸骨军马']={t=3000,icon='Ability_Mount_Undeadhorse'},
    ['棕马']={t=3000,icon='Ability_Mount_RidingHorse'},
    ['槲寄生狂欢者']={t=1000,icon='INV_Misc_Branch_01'},
    ['横扫']={t=1500,icon='Spell_Nature_Thorns'},
    ['横扫重锤']={t=1000,icon='Spell_Nature_CorrosiveBreath'},
    ['次元之门']={t=2000,icon='Temp'},
    ['次级巫师之油']={t=3000,icon='Temp'},
    ['次级治疗术']={t=2500,icon='Spell_Holy_LesserHeal'},
    ['次级治疗波']={t=1500,icon='Spell_Nature_HealingWaveLesser'},
    ['次级法力之油']={t=3000,icon='Temp'},
    ['次级隐形术']={t=3000,icon='Spell_Magic_LesserInvisibilty'},
    ['正义火焰']={t=4000,icon='Spell_Holy_InnerFire'},
    ['死亡之床']={t=2000,icon='Spell_Shadow_Twilight'},
    ['死亡之触']={t=3000,icon='Spell_Shadow_UnsummonBuilding'},
    ['死亡凋零']={t=2000,icon='Spell_Shadow_DeathAndDecay'},
    ['死亡显现']={t=1000,icon='Spell_Shadow_ShadeTrueSight'},
    ['死亡矿井炸药']={t=2000,icon='Spell_Fire_SelfDestruct'},
    ['死木诅咒']={t=2000,icon='Spell_Shadow_GatherShadows'},
    ['残废术']={t=3000,icon='Spell_Shadow_Cripple'},
    ['毒之克星']={t=2000,icon='Temp'},
    ['毒云术']={t=1000,icon='Spell_Nature_Regenerate'},
    ['毒性唾液']={t=500,icon='Spell_Nature_CorrosiveBreath'},
    ['毒性喷溅']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
    ['毒性射击']={t=2000,icon='Ability_Poisons'},
    ['毒性箭']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
    ['毒性钉刺']={t=2000,icon='INV_Misc_MonsterTail_03'},
    ['毒性鱼叉']={t=2000,icon='Ability_Poisons'},
    ['毒气炸弹']={t=1000,icon='INV_Misc_Ammo_Bullet_01'},
    ['毒液喷吐']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
    ['毒液箭']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
    ['毒蛇宝石']={t=5000,icon='Temp'},
    ['水下诱鱼器']={t=5000,icon='INV_Misc_Orb_03'},
    ['水下鱼珠']={t=5000,icon='INV_Misc_Spyglass_01'},
    ['水晶凝视']={t=2000,icon='Ability_GolemThunderClap'},
    ['水晶沉睡']={t=2000,icon='Spell_Nature_Sleep'},
    ['水晶闪耀']={t=2000,icon='Spell_Shadow_Teleport'},
    ['水果芳香']={t=1000,icon='INV_ValentinesChocolate02'},
    ['水泡']={t=1000,icon='Spell_Frost_Wisp'},
    ['永望镇传送']={t=10000,icon='Spell_Fire_SelfDestruct'},
    ['汲取魔法']={t=2000,icon='Spell_Shadow_DarkRitual'},
    ['沉默']={t=1500,icon='Spell_Holy_Silence'},
    ['沙尘之息']={t=2000,icon='Spell_Fire_WindsofWoe'},
    ['沙尘爆裂']={t=2000,icon='Spell_Nature_Cyclone'},
    ['沙恩的铃铛']={t=4500,icon='Temp'},
    ['沙虫横扫']={t=1000,icon='INV_Misc_MonsterScales_05'},
    ['沙赫拉姆之力']={t=1000,icon='Spell_Nature_WispSplode'},
    ['沙赫拉姆之拳']={t=1000,icon='Ability_Whirlwind'},
    ['沙赫拉姆烈焰']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['沙赫拉姆的意志']={t=1000,icon='Spell_Holy_MindVision'},
    ['沙赫拉姆的祝福']={t=1000,icon='Spell_Holy_LayOnHands'},
    ['沙赫拉姆诅咒']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
    ['治愈疾病']={t=2500,icon='Spell_Holy_NullifyDisease'},
    ['治疗之环']={t=3000,icon='Spell_Holy_BlessingOfProtection'},
    ['治疗之舌']={t=1000,icon='Spell_Holy_Heal'},
    ['治疗之舌 II']={t=1000,icon='Spell_Holy_Heal'},
    ['治疗之触']={t=3500,icon='Spell_Nature_HealingTouch'},
    ['治疗术']={t=3000,icon='Spell_Holy_Heal02'},
    ['治疗波']={t=3000,icon='Spell_Nature_MagicImmunity'},
    ['治疗祷言']={t=3000,icon='Spell_Holy_PrayerOfHealing02'},
    ['治疗结界']={t=2000,icon='Spell_Holy_LayOnHands'},
    ['治疗藤蔓']={t=500,icon='Temp'},
    ['治疗诅咒']={t=1000,icon='Spell_Shadow_AntiShadow'},
    ['治疗链']={t=2500,icon='Spell_Nature_HealingWaveGreater'},
    ['法力燃烧']={t=3000,icon='Spell_Shadow_ManaBurn'},
    ['法力燃烧链']={t=3000,icon='Spell_Shadow_ManaBurn'},
    ['法力风暴']={t=2000,icon='Spell_Frost_IceStorm'},
    ['法师视界']={t=3000,icon='Temp'},
    ['法术偏转']={t=1000,icon='Temp'},
    ['泰兰死亡']={t=2000,icon='Temp'},
    ['泰莉欧娜幻象']={t=3000,icon='Ability_Rogue_Disguise'},
    ['泰里恩幻象']={t=3000,icon='Ability_Rogue_Disguise'},
    ['泼洒净化过的水']={t=6000,icon='Temp'},
    ['浇醒林格']={t=2500,icon='Temp'},
    ['浸魔披风 - 次级防护']={t=5000,icon='Spell_Holy_GreaterHeal'},
    ['浸魔武器 - 屠兽']={t=5000,icon='Spell_Holy_GreaterHeal'},
    ['浸魔胸甲 - 次级精神']={t=5000,icon='Spell_Holy_GreaterHeal'},
    ['淤泥毒药']={t=2000,icon='Spell_Nature_Regenerate'},
    ['深度沉睡']={t=1000,icon='Spell_Shadow_Cripple'},
    ['混乱烈焰']={t=1000,icon='Spell_Fire_WindsofWoe'},
    ['游荡瘟疫']={t=2000,icon='Spell_Shadow_CallofBone'},
    ['激活防御']={t=5000,icon='Temp'},
    ['火上浇油！']={t=500,icon='Temp'},
    ['火元素']={t=3000,icon='Ability_Temp'},
    ['火印诅咒']={t=2000,icon='Ability_Creature_Cursed_03'},
    ['火岩粉']={t=5000,icon='Temp'},
    ['火息术']={t=1700,icon='Spell_Fire_Fire'},
    ['火炮']={t=2000,icon='Temp'},
    ['火烤甜面包']={t=1000,icon='INV_Misc_Food_11'},
    ['火焰之盾']={t=1000,icon='Spell_Fire_Immolation'},
    ['火焰之盾 II']={t=1000,icon='Spell_Fire_Immolation'},
    ['火焰之盾 III']={t=1000,icon='Spell_Fire_Immolation'},
    ['火焰之盾 IV']={t=1000,icon='Spell_Fire_Immolation'},
    ['火焰之雨']={t=3000,icon='Spell_Shadow_RainOfFire'},
    ['火焰增效']={t=1000,icon='Spell_Fire_Fireball'},
    ['火焰爆发']={t=1500,icon='Spell_Fire_FireBolt'},
    ['火焰的召唤']={t=2000,icon='Spell_Shadow_ChillTouch'},
    ['火焰破裂']={t=2500,icon='Spell_Fire_Fire'},
    ['火焰箭']={t=2000,icon='Spell_Fire_FireBolt'},
    ['火焰箭 II']={t=3000,icon='Spell_Fire_FireBolt02'},
    ['火焰箭 III']={t=3000,icon='Spell_Fire_FireBolt02'},
    ['火焰箭 IV']={t=3000,icon='Spell_Fire_FireBolt02'},
    ['火焰虚弱']={t=5000,icon='INV_Misc_QirajiCrystal_02'},
    ['火焰风暴']={t=2000,icon='Spell_Fire_SelfDestruct'},
    ['火球术']={t=3500,icon='Spell_Fire_FlameBolt'},
    ['火箭爆炸']={t=3000,icon='Temp'},
    ['火花']={t=2000,icon='Spell_Nature_Lightning'},
    ['灰尘之云']={t=1500,icon='Ability_Hibernation'},
    ['灰山羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['灰狼']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
    ['灰色科多兽']={t=3000,icon='Ability_Mount_Kodo_01'},
    ['灵魂之火']={t=6000,icon='Spell_Fire_Fireball02'},
    ['灵魂凋零']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
    ['灵魂击碎者']={t=2000,icon='Spell_Shadow_Haunting'},
    ['灵魂吞噬']={t=4000,icon='Ability_Racial_Cannibalize'},
    ['灵魂撕咬']={t=2000,icon='Spell_Shadow_SiphonMana'},
    ['灵魂支配']={t=3000,icon='Spell_Shadow_ShadowWordDominate'},
    ['灵魂消耗']={t=2000,icon='Spell_Shadow_LifeDrain02'},
    ['灵魂石复活']={t=3000,icon='Spell_Shadow_SoulGem'},
    ['灵魂破碎']={t=2000,icon='Spell_Fire_Fire'},
    ['灼烧']={t=1500,icon='Spell_Fire_SoulBurn'},
    ['灼热之痛']={t=1500,icon='Spell_Fire_SoulBurn'},
    ['灼热烈焰']={t=2000,icon='Spell_Fire_Immolation'},
    ['炉石']={t=10000,icon='INV_Misc_Rune_01'},
    ['炎爆术']={t=6000,icon='Spell_Fire_Fireball02'},
    ['炮击术']={t=3000,icon='Ability_GolemStormBolt'},
    ['炮击术 II']={t=3000,icon='Ability_GolemStormBolt'},
    ['炮火']={t=1000,icon='Spell_Fire_FireBolt02'},
    ['炸弹']={t=2000,icon='Spell_Fire_SelfDestruct'},
    ['炸弹攻击']={t=2000,icon='Spell_Fire_SelfDestruct'},
    ['炸药']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['点燃克罗苏斯']={t=3000,icon='Temp'},
    ['点燃躯体']={t=2000,icon='Spell_Fire_Fire'},
    ['炽热火焰']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['烈性炸药']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['烈焰冲击']={t=7000,icon='Spell_Fire_SelfDestruct'},
    ['烈焰印记']={t=1000,icon='Spell_Fire_Fireball'},
    ['烈焰喷射']={t=1700,icon='Spell_Fire_Fire'},
    ['烈焰喷溅']={t=3000,icon='Spell_Fire_FlameBolt'},
    ['烈焰尖刺']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['烈焰打击']={t=2200,icon='Spell_Fire_Fireball'},
    ['烈焰火炮']={t=1500,icon='Spell_Fire_FlameBolt'},
    ['烈焰爆击']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['烈焰鞭笞']={t=1000,icon='Spell_Fire_Fireball'},
    ['烈焰风暴']={t=3000,icon='Spell_Fire_SelfDestruct'},
    ['热疫']={t=4500,icon='Spell_Nature_NullifyDisease'},
    ['热疫疲倦']={t=3000,icon='Spell_Nature_NullifyDisease'},
    ['烹制甜点']={t=2000,icon='Spell_Holy_Heal'},
    ['焚化']={t=5000,icon='Temp'},
    ['焚烧']={t=2000,icon='Spell_Shadow_ChillTouch'},
    ['熄灭']={t=2000,icon='Temp'},
    ['熄灭永恒之火']={t=1000,icon='Temp'},
    ['熊怪形态']={t=2000,icon='INV_Misc_MonsterClaw_04'},
    ['熔化矿石']={t=1500,icon='Spell_Fire_SelfDestruct'},
    ['熔岩之雨']={t=2000,icon='Temp'},
    ['熔岩冲击']={t=1000,icon='Spell_Fire_FlameShock'},
    ['熔岩爆裂']={t=2000,icon='Spell_Fire_Fire'},
    ['熔解之语']={t=5000,icon='Temp'},
    ['熔铁之水']={t=2000,icon='Spell_Fire_Fireball'},
    ['燃烧之风']={t=1000,icon='Spell_Nature_Cyclone'},
    ['爆炸射击']={t=1000,icon='Spell_Fire_Fireball02'},
    ['爆竹']={t=500,icon='Temp'},
    ['爱情的重击']={t=1000,icon='INV_Ammo_Arrow_02'},
    ['爱神的飞刀']={t=1000,icon='Temp'},
    ['牛皮糖']={t=1000,icon='INV_SummerFest_Smorc'},
    ['特雷莱恩冰触术']={t=3000,icon='Spell_Shadow_UnsummonBuilding'},
    ['牺牲']={t=1000,icon='Spell_Holy_DivineIntervention'},
    ['狂热之刃']={t=1000,icon='Spell_Fire_Immolation'},
    ['狙击']={t=2000,icon='Ability_Marksmanship'},
    ['猛击']={t=1500,icon='Ability_Warrior_DecisiveStrike'},
    ['猫头鹰形态']={t=5000,icon='Spell_Nature_RavenForm'},
    ['献祭']={t=2000,icon='Spell_Fire_Immolation'},
    ['献祭丝囊']={t=10000,icon='Temp'},
    ['玛加萨火岩粉']={t=1300,icon='Temp'},
    ['玛拉索姆的爪牙']={t=1000,icon='Spell_Shadow_CorpseExplode'},
    ['玛格拉姆灵魂诅咒']={t=2000,icon='Spell_Shadow_UnholyFrenzy'},
    ['玫瑰凋零']={t=500,icon='INV_Misc_Dust_04'},
    ['瑟格拉·黑棘效果']={t=3000,icon='Temp'},
    ['瑟银手榴弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['瓦罗什的变形']={t=1000,icon='Temp'},
    ['瓦解']={t=3000,icon='Temp'},
    ['甜蜜惊喜']={t=1000,icon='INV_ValentinesChocolate03'},
    ['生命偷取']={t=1500,icon='Spell_Shadow_LifeDrain02'},
    ['生命封印']={t=2000,icon='Temp'},
    ['生命收割']={t=1000,icon='Spell_Shadow_Requiem'},
    ['生命符记']={t=10000,icon='Spell_Holy_Resurrection'},
    ['电击']={t=4000,icon='Spell_Nature_Purge'},
    ['疾病喷吐']={t=3000,icon='Spell_Shadow_CreepingPlague'},
    ['疾病射击']={t=2000,icon='Spell_Shadow_CallofBone'},
    ['疾病猛击']={t=1500,icon='Spell_Nature_EarthBind'},
    ['疾病软泥']={t=2000,icon='Spell_Shadow_CreepingPlague'},
    ['瘟疫中和器']={t=2000,icon='Spell_Holy_SearingLight'},
    ['瘟疫之云']={t=2000,icon='Spell_Shadow_CallofBone'},
    ['瘟疫心灵']={t=4000,icon='Spell_Shadow_CallofBone'},
    ['瘟疫鼠诅咒']={t=1500,icon='Spell_Shadow_UnholyFrenzy'},
    ['白山羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['白斑黑豹']={t=3000,icon='Ability_Mount_BlackPanther'},
    ['白色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['白色迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['白银万能钥匙']={t=5000,icon='Temp'},
    ['白马']={t=3000,icon='Ability_Mount_RidingHorse'},
    ['白骨碎片']={t=500,icon='Spell_Shadow_ScourgeBuild'},
    ['百万伏特']={t=2000,icon='Spell_Nature_ChainLightning'},
    ['盘蛇净化']={t=30000,icon='Spell_Shadow_LifeDrain'},
    ['真银万能钥匙']={t=5000,icon='Temp'},
    ['眼棱']={t=2000,icon='Spell_Nature_CallStorm'},
    ['瞄准射击']={t=3000,icon='INV_Spear_07'},
    ['知识试炼']={t=2000,icon='Spell_Nature_EarthBind'},
    ['石像鬼打击']={t=1500,icon='Spell_Shadow_ShadowBolt'},
    ['石肤术']={t=6000,icon='Spell_Nature_EnchantArmor'},
    ['破坏大件物品']={t=2000,icon='Spell_Shadow_CurseOfAchimonde'},
    ['破坏物品']={t=2000,icon='Spell_Shadow_CurseOfAchimonde'},
    ['破胆低吼']={t=1000,icon='Ability_Racial_Cannibalize'},
    ['碎石穴居怪伪装']={t=3000,icon='Ability_Rogue_Disguise'},
    ['神圣之火']={t=3500,icon='Spell_Holy_SearingLight'},
    ['神圣巫师之油']={t=3000,icon='Temp'},
    ['神圣愤怒']={t=2000,icon='Spell_Holy_Excorcism'},
    ['神圣武器']={t=3000,icon='Temp'},
    ['禁闭']={t=2000,icon='Spell_Shadow_Teleport'},
    ['种植魔法豆']={t=2000,icon='INV_Misc_Food_Wheat_02'},
    ['科多兽坐骑']={t=3000,icon='INV_Misc_Head_Tauren_02'},
    ['科多兽诱引器']={t=5000,icon='Trade_Fishing'},
    ['秘仪灵魂 II']={t=1000,icon='Spell_Holy_MagicalSentry'},
    ['秘仪灵魂 III']={t=1000,icon='Spell_Holy_MagicalSentry'},
    ['秘仪灵魂 IV']={t=1000,icon='Spell_Holy_MagicalSentry'},
    ['秘仪灵魂 V']={t=1000,icon='Spell_Holy_MagicalSentry'},
    ['秘银破片炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['空空如也的节日酒杯']={t=2000,icon='Temp'},
    ['简易传送']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
    ['简易传送他人']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
    ['简易传送小组']={t=2000,icon='Spell_Magic_LesserInvisibilty'},
    ['简易投掷炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['米布隆的诱饵']={t=2000,icon='INV_Misc_Food_50'},
    ['精灵之火']={t=2000,icon='Spell_Nature_FaerieFire'},
    ['精神偷取']={t=2000,icon='Spell_Shadow_Possession'},
    ['精神控制']={t=3000,icon='Spell_Shadow_ShadowWordDominate'},
    ['精神衰弱']={t=1000,icon='Spell_Shadow_MindSteal'},
    ['精神衰弱 II']={t=1000,icon='Spell_Shadow_MindSteal'},
    ['精神衰弱 III']={t=1000,icon='Spell_Shadow_MindSteal'},
    ['紫手']={t=4000,icon='Spell_Shadow_SiphonMana'},
    ['紫色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['紫色迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['紫色骷髅战马']={t=3000,icon='Ability_Mount_Undeadhorse'},
    ['纠缠根须']={t=1500,icon='Spell_Nature_StrangleVines'},
    ['红色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['红色迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['红色骷髅战马']={t=3000,icon='Ability_Mount_Undeadhorse'},
    ['红色骸骨军马']={t=3000,icon='Ability_Mount_Undeadhorse'},
    ['红蓝两色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['纳拉雷克斯的梦魇']={t=2000,icon='Spell_Nature_Sleep'},
    ['纳瑞安！']={t=3000,icon='INV_Misc_Head_Gnome_01'},
    ['绘制上古雕文']={t=10000,icon='Temp'},
    ['绘图工具包']={t=7000,icon='Temp'},
    ['统御意志']={t=2000,icon='Spell_Shadow_ShadowWordDominate'},
    ['绿色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['绿色科多兽']={t=3000,icon='Ability_Mount_Kodo_02'},
    ['绿色荧光机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['绿色迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['绿色骸骨战马']={t=3000,icon='Ability_Mount_Undeadhorse'},
    ['缠绕之藤']={t=1000,icon='Spell_Nature_Earthquake'},
    ['缩小']={t=3000,icon='Spell_Shadow_AntiShadow'},
    ['群体治疗']={t=1000,icon='Spell_Holy_GreaterHeal'},
    ['群体热疫']={t=1000,icon='Spell_Shadow_DarkSummoning'},
    ['群体驱魔']={t=1000,icon='Spell_Shadow_Teleport'},
    ['耐普图隆的守护']={t=1000,icon='Temp'},
    ['耶尼库的解脱']={t=4000,icon='Spell_Shadow_LifeDrain'},
    ['胁迫低吼']={t=1000,icon='Ability_Racial_Cannibalize'},
    ['能量虹吸']={t=1500,icon='Spell_Shadow_Cripple'},
    ['腐蚀术']={t=2000,icon='Spell_Shadow_AbominationExplosion'},
    ['腐蚀毒药']={t=1500,icon='Spell_Nature_CorrosiveBreath'},
    ['腐蚀酸液']={t=1500,icon='Spell_Nature_Acid_01'},
    ['腐蚀酸液喷溅']={t=3000,icon='Spell_Nature_Acid_01'},
    ['自我复活']={t=5000,icon='Temp'},
    ['自我爆炸']={t=7000,icon='Spell_Fire_SelfDestruct'},
    ['自毁']={t=7000,icon='Spell_Fire_SelfDestruct'},
    ['自然的平衡']={t=3000,icon='Temp'},
    ['自然的平衡失败']={t=10000,icon='Temp'},
    ['自然虚弱']={t=5000,icon='INV_Misc_QirajiCrystal_03'},
    ['自爆']={t=5000,icon='Spell_Fire_SelfDestruct'},
    ['自爆绵羊']={t=2000,icon='Ability_Repair'},
    ['致伤毒药']={t=3000,icon='INV_Misc_Herb_16'},
    ['致命武器']={t=3000,icon='Temp'},
    ['致命毒药']={t=3000,icon='Ability_Rogue_DualWeild'},
    ['致命毒药 II']={t=3000,icon='Ability_Rogue_DualWeild'},
    ['致命毒药 III']={t=3000,icon='Ability_Rogue_DualWeild'},
    ['致命毒药 IV']={t=3000,icon='Ability_Rogue_DualWeild'},
    ['致命毒药 V']={t=3000,icon='Ability_Rogue_DualWeild'},
    ['致密炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['致死毒素']={t=3000,icon='Spell_Nature_CorrosiveBreath'},
    ['致残毒药']={t=3000,icon='Ability_PoisonSting'},
    ['艾博希尔开始']={t=5000,icon='Spell_Nature_EarthBindTotem'},
    ['艾露恩的蜡烛']={t=500,icon='Temp'},
    ['艾露恩祷言']={t=1000,icon='Spell_Holy_Resurrection'},
    ['苦工伪装']={t=3000,icon='Ability_Rogue_Disguise'},
    ['茶色利刃豹']={t=3000,icon='Ability_Mount_JungleTiger'},
    ['荆棘诅咒']={t=2000,icon='Spell_Shadow_AntiShadow'},
    ['荣誉点数+138']={t=1000,icon='Temp'},
    ['荣誉点数+228']={t=1000,icon='Temp'},
    ['荣誉点数+2388']={t=1000,icon='INV_BannerPVP_02'},
    ['荣誉点数+378']={t=1000,icon='Temp'},
    ['荣誉点数+398']={t=1000,icon='Temp'},
    ['荣誉点数+50']={t=1000,icon='Temp'},
    ['荣誉点数+82']={t=1000,icon='Temp'},
    ['莫甘斯的爪牙']={t=2500,icon='Spell_Totem_WardOfDraining'},
    ['菲斯托姆复活']={t=3000,icon='Spell_Totem_WardOfDraining'},
    ['萨格拉斯之息']={t=2000,icon='Spell_Shadow_Metamorphosis'},
    ['萨瑞鲁斯的元素生物']={t=3000,icon='Spell_Shadow_RaiseDead'},
    ['萨纳瑞恩的治疗']={t=500,icon='Spell_Nature_MagicImmunity'},
    ['萨维亚的赐福']={t=5000,icon='Spell_Holy_FlashHeal'},
    ['落雷之云']={t=3000,icon='Spell_Nature_CallStorm'},
    ['蓝色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['蓝色科多兽']={t=3000,icon='Ability_Mount_Kodo_02'},
    ['蓝色骸骨军马']={t=3000,icon='Ability_Mount_Undeadhorse'},
    ['虚弱诅咒']={t=1000,icon='Spell_Shadow_CurseOfMannoroth'},
    ['虚空召唤']={t=3000,icon='Spell_Shadow_DeathCoil'},
    ['虚空宝石']={t=3000,icon='Temp'},
    ['虚空的召唤']={t=10000,icon='Temp'},
    ['虚空箭']={t=3000,icon='Spell_Shadow_ShadowBolt'},
    ['虚空行者守卫']={t=3000,icon='Spell_Shadow_SummonVoidWalker'},
    ['虫群风暴']={t=3000,icon='Spell_Nature_InsectSwarm'},
    ['蛮力狂扫']={t=4000,icon='Ability_Whirlwind'},
    ['蜜饯馅饼']={t=1000,icon='INV_Misc_Food_10'},
    ['蜥蜴之矢']={t=2000,icon='Spell_Nature_Lightning'},
    ['融合软泥怪']={t=500,icon='INV_Potion_12'},
    ['血之诅咒']={t=2000,icon='Spell_Shadow_RitualOfSacrifice'},
    ['血性狂吼']={t=1000,icon='Spell_Shadow_LifeDrain'},
    ['血色复活']={t=2000,icon='Spell_Holy_Resurrection'},
    ['补充精神']={t=3000,icon='Spell_Nature_MoonGlow'},
    ['补充精神 II']={t=3000,icon='Spell_Nature_MoonGlow'},
    ['裂盾传送门']={t=1500,icon='Spell_Arcane_TeleportOrgrimmar'},
    ['裂隙标记']={t=2000,icon='Spell_Nature_AbolishMagic'},
    ['装填']={t=3000,icon='Temp'},
    ['装满瓶子']={t=5000,icon='Temp'},
    ['装配NG-5炸药（红色）']={t=5000,icon='INV_Misc_Bomb_05'},
    ['装配NG-5炸药（蓝色）']={t=5000,icon='INV_Misc_Bomb_05'},
    ['褐色马']={t=3000,icon='Ability_Mount_RidingHorse'},
    ['覆体之网']={t=2000,icon='Spell_Nature_EarthBind'},
    ['视界术']={t=2000,icon='Spell_Nature_FarSight'},
    ['解散野兽']={t=5000,icon='Spell_Nature_SpiritWolf'},
    ['解除徽记']={t=1000,icon='Temp'},
    ['解除陷阱']={t=2000,icon='Spell_Shadow_GrimWard'},
    ['诱导幻象']={t=30000,icon='Spell_Shadow_LifeDrain'},
    ['诱惑']={t=1500,icon='Spell_Shadow_MindSteal'},
    ['诵读塞雷布拉斯之语']={t=3000,icon='Temp'},
    ['读取温度']={t=2000,icon='Temp'},
    ['调整态度']={t=2000,icon='INV_Gizmo_01'},
    ['调节']={t=7000,icon='INV_Gizmo_02'},
    ['豹笼钥匙']={t=5000,icon='Temp'},
    ['赤狼']={t=3000,icon='Ability_Mount_BlackDireWolf'},
    ['超度亡灵']={t=1500,icon='Spell_Holy_TurnUndead'},
    ['超强治疗结界']={t=2000,icon='Spell_Holy_LayOnHands'},
    ['超级水晶']={t=6000,icon='Temp'},
    ['跳跃闪电']={t=3000,icon='Spell_Nature_Lightning'},
    ['软泥之箭']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
    ['轰击软泥']={t=1000,icon='Temp'},
    ['辐射之箭']={t=3000,icon='Spell_Shadow_CorpseExplode'},
    ['辛迪加伪装']={t=3000,icon='Ability_Rogue_Disguise'},
    ['辛迪加炸弹']={t=3000,icon='Spell_Shadow_MindBomb'},
    ['达拉然巫师伪装']={t=3000,icon='Ability_Rogue_Disguise'},
    ['迅捷晨刃豹']={t=3000,icon='Ability_Mount_JungleTiger'},
    ['迅捷棕山羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['迅捷棕狼']={t=3000,icon='Ability_Mount_BlackDireWolf'},
    ['迅捷棕色科多兽']={t=3000,icon='Ability_Mount_Kodo_03'},
    ['迅捷棕马']={t=3000,icon='Ability_Mount_RidingHorse'},
    ['迅捷森林狼']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
    ['迅捷橙色迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['迅捷灰山羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['迅捷灰狼']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
    ['迅捷灰色科多兽']={t=3000,icon='Ability_Mount_Kodo_01'},
    ['迅捷白山羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['迅捷白色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['迅捷白色科多兽']={t=3000,icon='Ability_Mount_Kodo_01'},
    ['迅捷白马']={t=3000,icon='Ability_Mount_RidingHorse'},
    ['迅捷祖利安猛虎']={t=3000,icon='Ability_Mount_JungleTiger'},
    ['迅捷绿色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['迅捷绿色迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['迅捷蓝色迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['迅捷褐色马']={t=3000,icon='Ability_Mount_RidingHorse'},
    ['迅捷雷刃豹']={t=3000,icon='Ability_Mount_BlackPanther'},
    ['迅捷雾刃豹']={t=3000,icon='Ability_Mount_BlackPanther'},
    ['迅捷霜刃豹']={t=3000,icon='Ability_Mount_WhiteTiger'},
    ['迅捷黄色机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['迅猛龙的狡诈']={t=3000,icon='INV_Misc_MonsterClaw_02'},
    ['迅猛龙羽毛']={t=5000,icon='Temp'},
    ['远古豹']={t=3000,icon='Ability_Mount_JungleTiger'},
    ['连发寒冰箭']={t=2000,icon='Spell_Frost_FrostBolt02'},
    ['连珠火球']={t=3000,icon='Spell_Fire_FlameBolt'},
    ['迟钝术']={t=1000,icon='Spell_Shadow_Fumble'},
    ['迟钝术 II']={t=1000,icon='Spell_Shadow_Fumble'},
    ['迟钝术 III']={t=1000,icon='Spell_Shadow_Fumble'},
    ['迪菲亚盗贼伪装']={t=3000,icon='Ability_Rogue_Disguise'},
    ['逃命专家']={t=500,icon='Ability_Rogue_Trip'},
    ['速效毒素']={t=3000,icon='INV_Potion_19'},
    ['速效毒药']={t=3000,icon='Ability_Poisons'},
    ['速效毒药 II']={t=3000,icon='Ability_Poisons'},
    ['速效毒药 III']={t=3000,icon='Ability_Poisons'},
    ['速效毒药 IV']={t=3000,icon='Ability_Poisons'},
    ['速效毒药 V']={t=3000,icon='Ability_Poisons'},
    ['速效毒药 VI']={t=3000,icon='Ability_Poisons'},
    ['遗弃技能']={t=2500,icon='Spell_Shadow_AntiShadow'},
    ['遥控炸药']={t=1000,icon='INV_Misc_StoneTablet_04'},
    ['邪恶之眼']={t=1500,icon='Spell_Shadow_Charm'},
    ['邪恶诅咒']={t=1000,icon='Spell_Shadow_CurseOfMannoroth'},
    ['邪神法术反制']={t=300000,icon='Temp'},
    ['部族诅咒']={t=2000,icon='Spell_Shadow_CurseOfMannoroth'},
    ['酸性毒液喷溅']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
    ['酸液喷射']={t=3000,icon='Spell_Nature_Acid_01'},
    ['酸液喷涌']={t=2000,icon='Spell_Nature_Acid_01'},
    ['酸液溅射']={t=1000,icon='INV_Drink_06'},
    ['醉酒的车队员工']={t=2000,icon='Temp'},
    ['采矿']={t=3200,icon='Trade_Mining'},
    ['采集草药']={t=5000,icon='Spell_Nature_NatureTouchGrow'},
    ['释放乌米的雪人']={t=2000,icon='Temp'},
    ['释放小鬼']={t=2000,icon='Temp'},
    ['释放怒爪']={t=10000,icon='Temp'},
    ['释放温娜的猫']={t=1000,icon='Ability_Seal'},
    ['释放耶维尔']={t=2000,icon='Temp'},
    ['释放腐化软泥怪']={t=5000,icon='INV_Potion_19'},
    ['重击']={t=1000,icon='INV_Gauntlets_31'},
    ['重建']={t=3000,icon='Temp'},
    ['重新补给']={t=2000,icon='Spell_Misc_Drink'},
    ['重磅铁制炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['重磅青铜炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['野兽之爪']={t=1000,icon='Spell_Nature_Regeneration'},
    ['野兽之爪 II']={t=1000,icon='Spell_Nature_Regeneration'},
    ['野兽之爪 III']={t=1000,icon='Spell_Nature_Regeneration'},
    ['野兽之眼']={t=2000,icon='Ability_EyeOfTheOwl'},
    ['野兽幽魂 II']={t=3000,icon='Spell_Nature_SpiritWolf'},
    ['野性回复']={t=3000,icon='Spell_Nature_Rejuvenation'},
    ['野性幽魂']={t=3000,icon='Spell_Nature_SpiritWolf'},
    ['金色猎豹']={t=3000,icon='Ability_Mount_JungleTiger'},
    ['鉴定种类']={t=10000,icon='Spell_Lightning_LightningBolt01'},
    ['钢质机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['钩网']={t=500,icon='Ability_Ensnare'},
    ['钻地']={t=1000,icon='Ability_Vanish'},
    ['铁皮手雷']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['铜锣']={t=500,icon='Temp'},
    ['铸造维里甘之拳']={t=600,icon='Spell_Holy_RighteousFury'},
    ['长程射击 II']={t=4000,icon='Ability_Marksmanship'},
    ['长程射击 III']={t=4000,icon='Ability_Marksmanship'},
    ['长视术']={t=1000,icon='Ability_TownWatch'},
    ['闪光的小珠']={t=5000,icon='INV_Misc_Orb_03'},
    ['闪电吐息']={t=2000,icon='Spell_Nature_Lightning'},
    ['闪电图腾']={t=500,icon='Spell_Nature_Lightning'},
    ['闪电球']={t=1000,icon='Spell_Lightning_LightningBolt01'},
    ['闪电箭']={t=3000,icon='Spell_Nature_Lightning'},
    ['闪电链']={t=2500,icon='Spell_Nature_ChainLightning'},
    ['闪电震爆']={t=3200,icon='Spell_Nature_Lightning'},
    ['闪耀']={t=500,icon='Temp'},
    ['闪金镇传送门']={t=5000,icon='Temp'},
    ['阵风']={t=2000,icon='Spell_Nature_EarthBind'},
    ['阿克鲁比的传送']={t=2000,icon='Spell_Fire_SelfDestruct'},
    ['阿克鲁比的开锁']={t=4000,icon='Spell_Nature_MoonKey'},
    ['阿娜莎之箭']={t=500,icon='Temp'},
    ['阿鲁高的礼物']={t=2500,icon='Spell_Shadow_ChillTouch'},
    ['附有魔法的盖亚之种']={t=5000,icon='Temp'},
    ['附魔达隆郡的历史']={t=3500,icon='Temp'},
    ['陷地图腾']={t=500,icon='Spell_Nature_NatureTouchDecay'},
    ['隐形术']={t=3000,icon='Spell_Nature_Invisibilty'},
    ['雪人']={t=1500,icon='INV_Ammo_Snowball'},
    ['雷松的全视之眼']={t=1000,icon='Ability_Ambush'},
    ['雷松的猫头鹰']={t=1000,icon='Ability_Hunter_EagleEye'},
    ['雷矛军用坐骑']={t=3000,icon='Ability_Mount_MountainRam'},
    ['震击']={t=1000,icon='Temp'},
    ['震荡波']={t=2000,icon='Ability_Whirlwind'},
    ['霜刃豹']={t=3000,icon='Ability_Mount_WhiteTiger'},
    ['霜山羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['霜狼嗥叫者']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
    ['霜鬃之力']={t=1000,icon='Spell_Nature_UndyingStrength'},
    ['青山羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['青色迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['音乐催眠']={t=1000,icon='Temp'},
    ['顺劈斩']={t=2500,icon='Ability_Warrior_Cleave'},
    ['风暴之锤']={t=1000,icon='INV_Hammer_01'},
    ['食腐虫']={t=5000,icon='INV_Misc_Orb_03'},
    ['香料迫击炮']={t=500,icon='Spell_Fire_Fireball02'},
    ['驯鹿之尘效果']={t=8000,icon='Temp'},
    ['驱散']={t=1000,icon='Spell_Holy_DispelMagic'},
    ['驱散毒药']={t=2000,icon='Spell_Holy_Purify'},
    ['驱除灵魂']={t=4000,icon='Temp'},
    ['骑乘乌龟']={t=3000,icon='Ability_Hunter_Pet_Turtle'},
    ['骷髅矿工爆炸']={t=5000,icon='Spell_Fire_SelfDestruct'},
    ['骷髅马']={t=3000,icon='Ability_Mount_Undeadhorse'},
    ['骸骨战马']={t=3000,icon='Ability_Mount_Undeadhorse'},
    ['高爆炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['鬼魅幻影']={t=2000,icon='Spell_Shadow_BlackPlague'},
    ['鬼魅灵魂']={t=2000,icon='Spell_Shadow_BlackPlague'},
    ['魔化共鸣水晶']={t=5000,icon='Temp'},
    ['魔化迅捷']={t=3000,icon='Spell_Nature_Invisibilty'},
    ['魔爆术']={t=1500,icon='Spell_Nature_WispSplode'},
    ['鸦爪之触']={t=1500,icon='Spell_Shadow_Requiem'},
    ['鸦爪妖术']={t=2000,icon='Spell_Shadow_Charm'},
    ['麦伯克智慧饮料']={t=3000,icon='Temp'},
    ['麦琳瑟拉的觉醒']={t=2000,icon='Temp'},
    ['麻木之痛']={t=1500,icon='Spell_Nature_CorrosiveBreath'},
    ['麻痹毒药']={t=3000,icon='Spell_Nature_NullifyDisease'},
    ['麻痹毒药 II']={t=3000,icon='Spell_Nature_NullifyDisease'},
    ['麻痹毒药 III']={t=3000,icon='Spell_Nature_NullifyDisease'},
    ['麻风病治愈！']={t=2000,icon='Spell_Holy_FlashHeal'},
    ['黄金万能钥匙']={t=5000,icon='Temp'},
    ['黎明先锋']={t=1500,icon='Temp'},
    ['黑女巫的拥抱']={t=500,icon='Spell_Arcane_Blink'},
    ['黑山羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['黑斑黄豹']={t=3000,icon='Ability_Mount_JungleTiger'},
    ['黑暗主宰诅咒']={t=2000,icon='Spell_Shadow_AntiShadow'},
    ['黑暗回复']={t=2000,icon='Ability_Hunter_MendPet'},
    ['黑暗污泥']={t=5000,icon='Spell_Shadow_CreepingPlague'},
    ['黑暗治疗']={t=3500,icon='Spell_Shadow_ChillTouch'},
    ['黑暗泥浆']={t=1000,icon='Spell_Nature_StrangleVines'},
    ['黑暗美味朗姆酒']={t=1000,icon='INV_Drink_04'},
    ['黑暗耳语']={t=3000,icon='Spell_Shadow_Haunting'},
    ['黑标美味朗姆酒']={t=1000,icon='INV_Drink_04'},
    ['黑泥术']={t=3000,icon='Spell_Shadow_CallofBone'},
    ['黑狼']={t=3000,icon='Ability_Mount_BlackDireWolf'},
    ['黑箭']={t=2000,icon='Ability_TheBlackArrow'},
    ['黑纹虎']={t=3000,icon='Ability_Mount_JungleTiger'},
    ['黑色作战机械陆行鸟']={t=3000,icon='Ability_Mount_MechaStrider'},
    ['黑色作战科多兽']={t=3000,icon='Ability_Mount_Kodo_01'},
    ['黑色作战迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['黑色战狼']={t=3000,icon='Ability_Mount_BlackDireWolf'},
    ['黑色战羊']={t=3000,icon='Ability_Mount_MountainRam'},
    ['黑色战豹']={t=3000,icon='Ability_Mount_BlackPanther'},
    ['黑色战驹']={t=3000,icon='Ability_Mount_NightmareHorse'},
    ['黑色欲望']={t=1000,icon='INV_ValentinesChocolate04'},
    ['黑色迅猛龙']={t=3000,icon='Ability_Mount_Raptor'},
    ['黑色骷髅战马']={t=3000,icon='Ability_Mount_Undeadhorse'},
    ['黑豹']={t=3000,icon='Ability_Mount_BlackPanther'},
    ['黑铁地雷']={t=1000,icon='Spell_Shadow_Metamorphosis'},
    ['黑铁炸弹']={t=1000,icon='Spell_Fire_SelfDestruct'},
    ['黑铁矮人伪装']={t=3000,icon='Ability_Rogue_Disguise'},
    ['黑马']={t=3000,icon='Ability_Mount_NightmareHorse'},
    ['龙灵采集器900型']={t=2000,icon='Temp'},
    ['龙翼攻击']={t=1000,icon='INV_Misc_MonsterScales_14'},
  }